In [ ]:
import glob
import os
import pandas as pd
from sklearn.preprocessing import MinMaxScaler


### PATH

path = "reliability-cerebellar-volumetry/"
output = path + "outputs/"

# Where the subjects_METHOD.csv files are
sub_fold = path + 'data/'


deepCeres = output + "deepCeres/"

acapulco3 = output + "acapulco3/"
acapulco2 = output + "acapulco2/"

suit = output + "suit/"

ceres = output + "ceres/"

# True if you want to save the csv files
save = False

In [2]:
# Columns order
finalColumns = ['ID', 'ses', 'age', 'sex', 'ICV', 'Left.I.V', 'Right.I.V',
       'Left.VI', 'Right.VI',
       'Left.Crus.I', 'Right.Crus.I', 'Left.Crus.II', 'Right.Crus.II',
       'Left.VIIB', 'Right.VIIB', 'Left.VIIIA', 'Right.VIIIA', 'Left.VIIIB',
       'Right.VIIIB', 'Left.IX', 'Right.IX', 'Left.X', 'Right.X']

In [3]:
# Get sessions to use
def is_good_session(row):
    good_list = row["good_ses"].split(";")
    good_list = [f"{int(s):02d}" for s in good_list]
    return row["ses"] in good_list

# Preprocessing with all good subjects for each method

# ACAPULCO 0.3.0

In [4]:
# Get subjects list and information
subjects = pd.read_csv(sub_fold+'subjects_Acapulco_0.3.0.csv')
subjects_list = subjects['ID'].tolist()

print(subjects_list)
subjects

['sub-0025428', 'sub-0025432', 'sub-0025434', 'sub-0025435', 'sub-0025440', 'sub-0025445', 'sub-0025446', 'sub-0025447', 'sub-0025448', 'sub-0025449', 'sub-0025450', 'sub-0025455', 'sub-0025444', 'sub-0025454']

             ID  age sex   good_ses
0   sub-0025428   28   F  2;4;5;6;7
1   sub-0025432   21   M  1;3;4;5;6
2   sub-0025434   24   M  3;5;7;8;9
3   sub-0025435   30   F  1;2;3;4;5
4   sub-0025440   24   M  1;2;3;4;5
5   sub-0025445   23   F  1;2;4;5;6
6   sub-0025446   30   M  1;2;3;4;5
7   sub-0025447   26   M  1;2;3;4;5
8   sub-0025448   23   M  1;2;3;5;6
9   sub-0025449   22   M  2;3;4;5;6
10  sub-0025450   25   F  1;2;3;4;5
11  sub-0025455   25   M  1;2;3;4;5
12  sub-0025444   27   F  1;2;3;4;6
13  sub-0025454   26   M  1;2;3;4;5

In [5]:
# Columns to keep and convert
col = {
    'eTIV':'ICV',
    'Total_Cerebel_Vol':'Total_Cereb',
    'Rigt.IV' : 'Right.IV' # Error in ACAPULCO's outputs
}

# Column to drop
col_drop = ['Total_Cereb', 'Background', 'Corpus.Medullare', 'Vermis.IX', 'Vermis.VI', 'Vermis.VII', 'Vermis.VIII', 'Vermis.X']

In [6]:
# List to store DataFrames
all_data = []

# Loop through sessions
for ses in range(1, 11):
    ses_str = f"{ses:02d}"

    # Read CSV for given session
    data = pd.read_csv(acapulco3 + 'Cerebel_vols_ses-' + ses_str + '.csv', index_col=0)

    # Keep chosen subjects
    data = data[data["ID"].isin(subjects_list)].reset_index(drop=True)

    # Rename the columns in col and drop col_drop
    data = data.rename(columns=col)
    data = data.drop(col_drop, axis=1)

    # Group I.III, IV and V into I.V
    data.insert(4, "Left.I.V", data["Left.I.III"] + data["Left.IV"] + data["Left.V"])
    data.insert(4, "Right.I.V", data["Right.I.III"] + data["Right.IV"] + data["Right.V"])
    data = data.drop(["Left.I.III", "Left.IV", "Left.V", "Right.I.III", "Right.IV", "Right.V"], axis = 1)

    # Add Session column at the beginning
    data.insert(1, 'ses', ses_str)

    # Append to the list
    all_data.append(data)

# Concatenate all DataFrames into one
acapulco3_df = pd.concat(all_data, ignore_index=True)

# Sort given id and session
acapulco3_df = acapulco3_df.sort_values(by=["ID", "ses"], ascending=[True, True]).reset_index(drop=True)

# Merge with age and sex
acapulco3_df = acapulco3_df.merge(subjects, on="ID", how="left")

acapulco3_df = acapulco3_df[acapulco3_df.apply(is_good_session, axis=1)].reset_index(drop=True)

# Sort columns
acapulco3_df = acapulco3_df[finalColumns]

for i in range(4,acapulco3_df.shape[1]):
    acapulco3_df.isetitem(i, acapulco3_df.iloc[:,i].astype(float))

# Save it
if save :
    acapulco3_df.to_csv(acapulco3+'acapulco3_all_volumes_cm3_ALLGOODDATA.csv', index=False)

acapulco3_df

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,1.370856e+06,9313.0,8026.0,9231.0,10486.0,12131.0,...,6539.0,7407.0,5408.0,4279.0,2008.0,2247.0,3833.0,3315.0,386.0,498.0
1,sub-0025428,04,28,F,1.388105e+06,9392.0,7642.0,9471.0,10498.0,12199.0,...,6662.0,7111.0,5751.0,4940.0,2015.0,2215.0,3435.0,3102.0,397.0,460.0
2,sub-0025428,05,28,F,1.382804e+06,9337.0,7851.0,9423.0,10656.0,12833.0,...,6732.0,7335.0,5057.0,4733.0,2163.0,2509.0,3681.0,3197.0,374.0,490.0
3,sub-0025428,06,28,F,1.394185e+06,9784.0,7659.0,8945.0,10623.0,12135.0,...,6331.0,7412.0,5683.0,4809.0,2378.0,2152.0,3685.0,3460.0,373.0,482.0
4,sub-0025428,07,28,F,1.378490e+06,9375.0,7910.0,9090.0,10384.0,12045.0,...,6257.0,6990.0,5180.0,5151.0,1446.0,2382.0,3325.0,2716.0,398.0,445.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,sub-0025455,01,25,M,1.553103e+06,7149.0,6425.0,9115.0,9112.0,10424.0,...,4569.0,5575.0,4879.0,4032.0,3217.0,2919.0,3199.0,2977.0,430.0,412.0
66,sub-0025455,02,25,M,1.558955e+06,7338.0,6779.0,8720.0,8781.0,10717.0,...,5808.0,6132.0,5728.0,4915.0,3031.0,3108.0,3153.0,3066.0,406.0,422.0
67,sub-0025455,03,25,M,1.550227e+06,7034.0,6528.0,9029.0,9241.0,10268.0,...,5680.0,5831.0,5842.0,5026.0,2292.0,2945.0,3185.0,2927.0,385.0,404.0
68,sub-0025455,04,25,M,1.540075e+06,7030.0,6338.0,9287.0,9056.0,10247.0,...,6254.0,5878.0,5057.0,4691.0,2195.0,2923.0,3157.0,3024.0,368.0,392.0
69,sub-0025455,05,25,M,1.551094e+06,7362.0,6696.0,8464.0,8563.0,10619.0,...,5812.0,5764.0,5519.0,4598.0,2458.0,3154.0,3109.0,3095.0,362.0,423.0

In [7]:
# Scale data
scaler = MinMaxScaler()

# Divide by ICV and scale
acapulco3_scaled = acapulco3_df.copy()
acapulco3_scaled.iloc[:, 4:] = scaler.fit_transform(acapulco3_scaled.iloc[:, 4:].div(acapulco3_scaled.ICV, axis=0))

# Save the dataframe
if save :
    acapulco3_scaled.to_csv(acapulco3+'acapulco3_all_volumes_cm3_scaled_ALLGOODDATA.csv', index=False)

acapulco3_scaled

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,0.0,0.935958,0.824361,0.945645,0.980246,0.844628,...,0.948947,0.775777,0.689094,0.317869,0.343872,0.368294,1.000000,0.947130,0.530610,0.949953
1,sub-0025428,04,28,F,0.0,0.928098,0.684929,0.984632,0.950216,0.822656,...,0.964174,0.673186,0.777492,0.568153,0.337874,0.347593,0.805966,0.814736,0.557166,0.790210
2,sub-0025428,05,28,F,0.0,0.924144,0.753667,0.980892,1.000000,1.000000,...,1.000000,0.739642,0.560602,0.490302,0.389187,0.451868,0.919069,0.870485,0.463935,0.905249
3,sub-0025428,06,28,F,0.0,1.000000,0.680213,0.806767,0.969913,0.792305,...,0.830074,0.744007,0.747661,0.505506,0.453648,0.322733,0.907685,0.992973,0.446383,0.862015
4,sub-0025428,07,28,F,0.0,0.938058,0.777838,0.884652,0.939808,0.804488,...,0.829047,0.654143,0.605530,0.669942,0.154374,0.410654,0.768219,0.623948,0.573489,0.747280
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,sub-0025455,01,25,M,0.0,0.310100,0.138811,0.567727,0.360857,0.074432,...,0.000000,0.112189,0.330497,0.017280,0.620303,0.482872,0.555568,0.585374,0.502341,0.459042
66,sub-0025455,02,25,M,0.0,0.339801,0.223233,0.447382,0.279415,0.133076,...,0.406807,0.237989,0.568275,0.335805,0.562385,0.537305,0.533091,0.621373,0.403724,0.486185
67,sub-0025455,03,25,M,0.0,0.291345,0.168388,0.548243,0.393558,0.042659,...,0.374835,0.175048,0.610325,0.386933,0.350122,0.492529,0.552423,0.564669,0.331235,0.435657
68,sub-0025455,04,25,M,0.0,0.299148,0.130232,0.638224,0.365468,0.053478,...,0.580836,0.195287,0.393937,0.274695,0.325859,0.491690,0.549624,0.619092,0.274820,0.405231
69,sub-0025455,05,25,M,0.0,0.351038,0.210673,0.387649,0.240493,0.122864,...,0.417946,0.158474,0.516452,0.228004,0.398519,0.556260,0.522156,0.642054,0.241422,0.496287

# ACAPULCO 0.2.0

In [8]:
# Get subjects list and information
subjects = pd.read_csv(sub_fold+'subjects_Acapulco_0.2.0.csv')
subjects_list = subjects['ID'].tolist()

print(subjects_list)
subjects

['sub-0025428', 'sub-0025432', 'sub-0025434', 'sub-0025435', 'sub-0025440', 'sub-0025446', 'sub-0025447', 'sub-0025448', 'sub-0025449', 'sub-0025450', 'sub-0025455', 'sub-0025444', 'sub-0025454', 'sub-0025442', 'sub-0025443']

             ID  age sex   good_ses
0   sub-0025428   28   F  2;4;5;6;7
1   sub-0025432   21   M  1;3;4;5;6
2   sub-0025434   24   M  3;5;7;8;9
3   sub-0025435   30   F  1;2;3;4;5
4   sub-0025440   24   M  1;2;3;4;5
5   sub-0025446   30   M  1;2;3;4;5
6   sub-0025447   26   M  1;2;3;4;5
7   sub-0025448   23   M  1;2;3;5;6
8   sub-0025449   22   M  2;3;4;5;6
9   sub-0025450   25   F  1;2;3;4;5
10  sub-0025455   25   M  1;2;3;4;5
11  sub-0025444   27   F  1;2;3;4;6
12  sub-0025454   26   M  1;2;3;4;5
13  sub-0025442   27   F  1;2;3;4;5
14  sub-0025443   25   M  1;3;4;5;6

In [9]:
# Columns to keep and convert
col = {
    'eTIV':'ICV',
    'Total_Cerebel_Vol':'Total_Cereb',
    'Rigt.IV' : 'Right.IV' # Error in ACAPULCO's outputs
}

# Column to drop
col_drop = ['Total_Cereb', 'Background', 'Corpus.Medullare', 'Vermis.IX', 'Vermis.VI', 'Vermis.VII', 'Vermis.VIII', 'Vermis.X']

In [10]:
# List to store DataFrames
all_data = []

# Loop through sessions
for ses in range(1, 11):
    ses_str = f"{ses:02d}"

    # Read CSV for given session
    data = pd.read_csv(acapulco2 + 'ses-' + ses_str + '/QC+vols/Cerebel_vols.csv', index_col=0)

    # Keep chosen subjects
    data = data[data["ID"].isin(subjects_list)].reset_index(drop=True)

    # Rename the columns in col and drop col_drop
    data = data.rename(columns=col)
    data = data.drop(col_drop, axis=1)

    # Group I.III, IV and V into I.V
    data.insert(4, "Left.I.V", data["Left.I.III"] + data["Left.IV"] + data["Left.V"])
    data.insert(4, "Right.I.V", data["Right.I.III"] + data["Right.IV"] + data["Right.V"])
    data = data.drop(["Left.I.III", "Left.IV", "Left.V", "Right.I.III", "Right.IV", "Right.V"], axis = 1)

    # Add Session column at the beginning
    data.insert(1, 'ses', ses_str)

    # Append to the list
    all_data.append(data)

# Concatenate all DataFrames into one
acapulco2_df = pd.concat(all_data, ignore_index=True)

# Sort given id and session
acapulco2_df = acapulco2_df.sort_values(by=["ID", "ses"], ascending=[True, True]).reset_index(drop=True)

# Merge with age and sex
acapulco2_df = acapulco2_df.merge(subjects, on="ID", how="left")

acapulco2_df = acapulco2_df[acapulco2_df.apply(is_good_session, axis=1)].reset_index(drop=True)

# Sort columns
acapulco2_df = acapulco2_df[finalColumns]

for i in range(4,acapulco2_df.shape[1]):
    acapulco2_df.isetitem(i, acapulco2_df.iloc[:,i].astype(float))

# Save it
if save :
    acapulco2_df.to_csv(acapulco2+'acapulco2_all_volumes_cm3_ALLGOODDATA.csv', index=False)

acapulco2_df

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,1.370855e+06,9597.0,8315.0,9377.0,10566.0,12626.0,...,6652.0,6995.0,5530.0,4269.0,2198.0,2224.0,3817.0,3410.0,410.0,502.0
1,sub-0025428,04,28,F,1.388104e+06,9406.0,8135.0,9623.0,10709.0,12825.0,...,6659.0,7054.0,5751.0,4752.0,2039.0,2175.0,3445.0,3222.0,434.0,453.0
2,sub-0025428,05,28,F,1.382804e+06,9810.0,8332.0,9494.0,10522.0,13393.0,...,7236.0,7148.0,4823.0,4728.0,2393.0,2508.0,3825.0,3502.0,405.0,500.0
3,sub-0025428,06,28,F,1.394185e+06,9950.0,8391.0,9125.0,10341.0,12794.0,...,6667.0,7277.0,5437.0,4493.0,2320.0,2315.0,3613.0,3408.0,375.0,515.0
4,sub-0025428,07,28,F,1.378490e+06,9326.0,8099.0,9899.0,10874.0,13032.0,...,6602.0,7635.0,5320.0,4858.0,1136.0,2223.0,3149.0,2656.0,362.0,482.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,sub-0025455,01,25,M,1.553102e+06,7240.0,6562.0,9110.0,9218.0,10920.0,...,5888.0,5847.0,5372.0,4463.0,2829.0,3128.0,3356.0,3197.0,423.0,403.0
71,sub-0025455,02,25,M,1.558955e+06,7401.0,6911.0,8900.0,9010.0,11120.0,...,5788.0,6345.0,5720.0,4613.0,3274.0,3275.0,3254.0,3138.0,429.0,433.0
72,sub-0025455,03,25,M,1.550226e+06,7287.0,6623.0,9164.0,9308.0,10445.0,...,6175.0,5744.0,6293.0,5252.0,2349.0,3259.0,3257.0,3059.0,385.0,434.0
73,sub-0025455,04,25,M,1.540074e+06,7023.0,6424.0,9460.0,9338.0,10678.0,...,6308.0,5811.0,5454.0,4557.0,2421.0,3017.0,3142.0,3108.0,407.0,405.0
74,sub-0025455,05,25,M,1.551094e+06,7233.0,6810.0,8638.0,8786.0,11412.0,...,5940.0,5836.0,6038.0,4521.0,2574.0,3234.0,3144.0,3150.0,400.0,435.0

In [11]:
# Scale data
scaler = MinMaxScaler()

# Divide by ICV and scale
acapulco2_scaled = acapulco2_df.copy()
acapulco2_scaled.iloc[:, 4:] = scaler.fit_transform(acapulco2_scaled.iloc[:, 4:].div(acapulco2_scaled.ICV, axis=0))

# Save the dataframe
if save :
    acapulco2_scaled.to_csv(acapulco2+'acapulco2_all_volumes_cm3_scaled_ALLGOODDATA.csv', index=False)

acapulco2_scaled

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,0.0,0.960253,0.873827,0.866418,0.939452,0.847220,...,0.804037,0.612893,0.721463,0.552365,0.359879,0.081997,1.000000,0.926244,0.555920,0.853348
1,sub-0025428,04,28,F,0.0,0.894637,0.785189,0.902566,0.941877,0.856517,...,0.775573,0.605768,0.774205,0.675874,0.299216,0.046650,0.777728,0.804716,0.632972,0.623691
2,sub-0025428,05,28,F,0.0,0.987582,0.856484,0.876415,0.906481,1.000000,...,1.000000,0.635574,0.457405,0.674183,0.417246,0.203961,0.986576,0.959147,0.520722,0.826778
3,sub-0025428,06,28,F,0.0,1.000000,0.853515,0.750700,0.842182,0.836408,...,0.767751,0.652726,0.656573,0.595720,0.387252,0.106295,0.858292,0.894786,0.384996,0.871771
4,sub-0025428,07,28,F,0.0,0.891489,0.791569,1.000000,1.000000,0.925530,...,0.771507,0.761486,0.637004,0.716119,0.008321,0.075808,0.632712,0.516575,0.348845,0.758047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,sub-0025455,01,25,M,0.0,0.276869,0.078230,0.484404,0.345711,0.146418,...,0.257299,0.156926,0.443404,0.456313,0.458286,0.331639,0.541959,0.612802,0.404205,0.238357
71,sub-0025455,02,25,M,0.0,0.301928,0.168147,0.422971,0.293550,0.179186,...,0.216923,0.260976,0.545056,0.490431,0.583974,0.386918,0.487939,0.579507,0.420249,0.343644
72,sub-0025455,03,25,M,0.0,0.288253,0.098628,0.502323,0.368848,0.052077,...,0.356294,0.136663,0.733758,0.661704,0.320127,0.387878,0.497994,0.550557,0.267920,0.356374
73,sub-0025455,04,25,M,0.0,0.247225,0.054946,0.592936,0.388633,0.115013,...,0.414309,0.159813,0.483295,0.490397,0.345724,0.296561,0.453316,0.583305,0.358307,0.258491
74,sub-0025455,05,25,M,0.0,0.277314,0.149711,0.368101,0.254984,0.251351,...,0.277098,0.156170,0.653173,0.472732,0.385185,0.376857,0.443617,0.592612,0.322030,0.359187

# SUIT

In [12]:
# Get subjects list and information
subjects = pd.read_csv(sub_fold+'subjects_Suit.csv')
subjects_list = subjects['ID'].tolist()

print(subjects_list)
subjects

['sub-0025428', 'sub-0025432', 'sub-0025434', 'sub-0025435', 'sub-0025440', 'sub-0025445', 'sub-0025446', 'sub-0025447', 'sub-0025448', 'sub-0025449', 'sub-0025450', 'sub-0025455', 'sub-0025439', 'sub-0025443', 'sub-0025452', 'sub-0025456']

             ID  age sex   good_ses
0   sub-0025428   28   F  2;4;5;6;7
1   sub-0025432   21   M  1;3;4;5;6
2   sub-0025434   24   M  3;5;7;8;9
3   sub-0025435   30   F  1;2;3;4;5
4   sub-0025440   24   M  1;2;3;4;5
5   sub-0025445   23   F  1;2;4;5;6
6   sub-0025446   30   M  1;2;3;4;5
7   sub-0025447   26   M  1;2;3;4;5
8   sub-0025448   23   M  1;2;3;5;6
9   sub-0025449   22   M  2;3;4;5;6
10  sub-0025450   25   F  1;2;3;4;5
11  sub-0025455   25   M  1;2;3;4;5
12  sub-0025439   24   F  2;3;4;6;7
13  sub-0025443   25   M  1;3;4;5;6
14  sub-0025452   22   F  1;2;3;4;5
15  sub-0025456   22   F  1;2;3;4;5

In [13]:
# Columns to keep and convert
col = {
    '1.0' : 'Left.I.IV',
    '2.0' : 'Right.I.IV',
    '3.0' : 'Left.V',
    '4.0' : 'Right.V',
    '5.0' : 'Left.VI',
    '6.0' : 'Vermis.VI',
    '7.0' : 'Right.VI',
    '8.0' : 'Left.Crus.I',
    '9.0' : 'Vermis.Crus.I',
    '10.0' : 'Right.Crus.I',
    '11.0' : 'Left.Crus.II',
    '12.0' : 'Vermis.Crus.II',
    '13.0' : 'Right.Crus.II',
    '14.0' : 'Left.VIIB',
    '15.0' : 'Vermis.VIIB',
    '16.0' : 'Right.VIIB',
    '17.0' : 'Left.VIIIA',
    '18.0' : 'Vermis.VIIIA',
    '19.0' : 'Right.VIIIA',
    '20.0' : 'Left.VIIIB',
    '21.0' : 'Vermis.VIIIB',
    '22.0' : 'Right.VIIIB',
    '23.0' : 'Left.IX',
    '24.0' : 'Vermis.IX',
    '25.0' : 'Right.IX',
    '26.0' : 'Left.X',
    '27.0' : 'Vermis.X',
    '28.0' : 'Right.X'
}

In [14]:
# List to store DataFrames
all_data = []

# Loop through subjects and sessions
for sub in subjects_list:
    sessions = subjects[subjects['ID']==sub]['good_ses'].iloc[0].split(';')
    for ses in sessions:
            ses_str = f"{int(ses):02d}"

            # Get the matching file (for given subject and given session)
            dataFile = os.path.join(suit, sub, f"ses-{ses_str}", f"{sub}_ses-{ses_str}_volumes.csv")

            # Read CSV
            data = pd.read_csv(dataFile)
            
            # Keep only the columns in col and rename them
            data = data[list(col.keys())].rename(columns=col)

            # Group I.III, IV and V into I.V
            data.insert(4, "Left.I.V", data["Left.I.IV"] + data["Left.V"])
            data.insert(4, "Right.I.V", data["Right.I.IV"] + data["Right.V"])
            data = data.drop(["Left.I.IV", "Left.V", "Right.I.IV", "Right.V"], axis = 1)

            # Add Subject ID and Session columns at the beginning
            data.insert(0, 'ses', ses_str)
            data.insert(0, 'ID', sub)

            # Append to the list
            all_data.append(data)

# Concatenate all DataFrames into one
suit_df = pd.concat(all_data, ignore_index=True)

# Add ICV from acapulco
suit_df.insert(4, 'ICV', acapulco3_df['ICV'])

# Sort given id and session
suit_df = suit_df.sort_values(by=["ID", "ses"], ascending=[True, True]).reset_index(drop=True)

# Merge with age and sex
suit_df= suit_df.merge(subjects, on="ID", how="left")

# Sort columns
suit_df = suit_df[finalColumns]

# Save it
if save :
    suit_df.to_csv(suit+'suit_all_volumes_cm3_ALLGOODDATA.csv', index=False)

suit_df

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,1.370856e+06,1.208054,1.185940,0.676470,0.651703,0.655798,...,0.700961,0.669952,0.701355,0.672463,0.638406,0.608524,0.575977,0.621894,0.547930,0.528146
1,sub-0025428,04,28,F,1.388105e+06,1.199541,1.176284,0.677726,0.655497,0.660897,...,0.693731,0.655724,0.704053,0.676164,0.630693,0.611455,0.570927,0.615120,0.539170,0.512622
2,sub-0025428,05,28,F,1.382804e+06,1.181272,1.151466,0.674730,0.656717,0.664996,...,0.703607,0.681044,0.717994,0.678886,0.651621,0.605657,0.589995,0.609097,0.532673,0.490535
3,sub-0025428,06,28,F,1.394185e+06,1.198158,1.177947,0.682938,0.665247,0.666670,...,0.680542,0.669607,0.715784,0.680477,0.639928,0.603814,0.579066,0.612285,0.513464,0.519492
4,sub-0025428,07,28,F,1.378490e+06,1.196252,1.163871,0.678749,0.658918,0.664879,...,0.667896,0.643821,0.658613,0.675816,0.570722,0.604663,0.531652,0.590116,0.510917,0.484815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,sub-0025456,01,22,F,NaN,1.178938,1.184450,0.666229,0.648741,0.600039,...,0.677297,0.670225,0.660148,0.694009,0.641961,0.640686,0.582719,0.607339,0.536892,0.488083
76,sub-0025456,02,22,F,NaN,1.171875,1.203068,0.661732,0.642590,0.621769,...,0.676541,0.669272,0.681797,0.691484,0.625893,0.651533,0.563912,0.621938,0.538424,0.523867
77,sub-0025456,03,22,F,NaN,1.196302,1.195304,0.662023,0.645714,0.616170,...,0.678521,0.674202,0.685307,0.697725,0.632459,0.648402,0.570518,0.608564,0.525643,0.519035
78,sub-0025456,04,22,F,NaN,1.189436,1.209503,0.665505,0.641666,0.618682,...,0.670854,0.661820,0.679539,0.699005,0.619015,0.659912,0.571809,0.623490,0.494334,0.507379
79,sub-0025456,05,22,F,NaN,1.197724,1.214380,0.666149,0.646153,0.613443,...,0.680478,0.665130,0.680383,0.695945,0.629000,0.652403,0.574255,0.609412,0.527197,0.521521

In [15]:
# Scale data
scaler = MinMaxScaler()

# Divide by ICV and scale
suit_scaled = suit_df.copy()
suit_scaled.iloc[:,4:] = scaler.fit_transform(suit_scaled.iloc[:,4:].div(suit_scaled.ICV, axis=0))

# Save
if save :
    suit_scaled.to_csv(suit+'suit_all_volumes_cm3_scaled_ALLGOODDATA.csv', index=False)

suit_scaled

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,0.0,1.000000,0.826371,0.917907,0.744882,0.700419,...,0.811963,0.685370,0.901126,0.719457,0.918095,0.739708,0.892126,0.818220,0.727618,0.802083
1,sub-0025428,04,28,F,0.0,0.937270,0.765650,0.887176,0.725613,0.689618,...,0.755849,0.607965,0.880066,0.703319,0.858690,0.722315,0.834027,0.767227,0.661504,0.715188
2,sub-0025428,05,28,F,0.0,0.900921,0.715239,0.885442,0.741954,0.712393,...,0.799806,0.703385,0.937451,0.721370,0.947069,0.709526,0.934801,0.754346,0.642689,0.635988
3,sub-0025428,06,28,F,0.0,0.919790,0.757066,0.896636,0.755561,0.699434,...,0.699361,0.645417,0.909659,0.707879,0.883001,0.684507,0.860545,0.747999,0.543481,0.733234
4,sub-0025428,07,28,F,0.0,0.950640,0.755038,0.911558,0.760668,0.719149,...,0.681811,0.582640,0.739645,0.718118,0.647454,0.712843,0.665982,0.694271,0.557231,0.619452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,sub-0025456,01,22,F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,sub-0025456,02,22,F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,sub-0025456,03,22,F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,sub-0025456,04,22,F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,sub-0025456,05,22,F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# CERES

In [16]:
# Get subjects list and information
subjects = pd.read_csv(sub_fold+'subjects_Ceres.csv')
subjects_list = subjects['ID'].tolist()

print(subjects_list)
subjects

['sub-0025428', 'sub-0025432', 'sub-0025434', 'sub-0025435', 'sub-0025440', 'sub-0025445', 'sub-0025446', 'sub-0025447', 'sub-0025448', 'sub-0025449', 'sub-0025450', 'sub-0025455', 'sub-0025439', 'sub-0025443', 'sub-0025444', 'sub-0025452', 'sub-0025453', 'sub-0025454', 'sub-0025456']

             ID  age sex   good_ses
0   sub-0025428   28   F  2;4;5;6;7
1   sub-0025432   21   M  1;3;4;5;6
2   sub-0025434   24   M  3;5;7;8;9
3   sub-0025435   30   F  1;2;3;4;5
4   sub-0025440   24   M  1;2;3;4;5
5   sub-0025445   23   F  1;2;4;5;6
6   sub-0025446   30   M  1;2;3;4;5
7   sub-0025447   26   M  1;2;3;4;5
8   sub-0025448   23   M  1;2;3;5;6
9   sub-0025449   22   M  2;3;4;5;6
10  sub-0025450   25   F  1;2;3;4;5
11  sub-0025455   25   M  1;2;3;4;5
12  sub-0025439   24   F  2;3;4;6;7
13  sub-0025443   25   M  1;3;4;5;6
14  sub-0025444   27   F  1;2;3;4;6
15  sub-0025452   22   F  1;2;3;4;5
16  sub-0025453   26   F  1;3;4;5;6
17  sub-0025454   26   M  1;2;3;4;5
18  sub-0025456   22   F  1;2;3;4;5

In [17]:
# Columns to keep and convert
col = {
    'ICV cm3':'ICV',
    'I-II right cm3':'Right.I.II',
    'I-II left cm3':'Left.I.II',
    'III right cm3':'Right.III',
    'III left cm3':'Left.III',
    'IV right cm3':'Right.IV',
    'IV left cm3':'Left.IV',
    'V right cm3':'Right.V',
    'V left cm3':'Left.V',
    'VI right cm3':'Right.VI',
    'VI left cm3':'Left.VI',
    'Crus I right cm3':'Right.Crus.I',
    'Crus I left cm3':'Left.Crus.I',
    'Crus II right cm3':'Right.Crus.II',
    'Crus II left cm3':'Left.Crus.II',
    'VIIB right cm3':'Right.VIIB',
    'VIIB left cm3':'Left.VIIB',
    'VIIIA right cm3':'Right.VIIIA',
    'VIIIA left cm3':'Left.VIIIA',
    'VIIIB right cm3':'Right.VIIIB',
    'VIIIB left cm3':'Left.VIIIB',
    'IX right cm3':'Right.IX',
    'IX left cm3':'Left.IX',
    'X right cm3':'Right.X',
    'X left cm3':'Left.X',
}

In [18]:
# List to store DataFrames
all_data = []

# Loop through subjects and sessions
for sub in subjects_list:
    sessions = subjects[subjects['ID']==sub]['good_ses'].iloc[0].split(';')
    for ses in sessions:
        ses_str = f"{int(ses):02d}"
        
        # Get the matching file (for given subject and given session)
        dataFile = glob.glob(os.path.join(ceres, 'output', f"{sub}_ses-{ses_str}_T1w_job*_archive", "report_job*.csv"))[0]

        # Read CSV
        data = pd.read_csv(dataFile, sep=';')

        # Keep only the columns in col and rename them
        data = data[list(col.keys())].rename(columns=col)

        # Group I.II, III, IV and V into I.V
        data.insert(4, "Left.I.V", data["Left.I.II"] + data["Left.III"] + data["Left.IV"] + data["Left.V"])
        data.insert(4, "Right.I.V", data["Right.I.II"] + data["Right.III"] + data["Right.IV"] + data["Right.V"])
        data = data.drop(["Left.I.II", "Left.III", "Left.IV", "Left.V", "Right.I.II", "Right.III", "Right.IV", "Right.V"], axis = 1)

        # Add Subject ID and Session columns at the beginning
        data.insert(0, 'ses', ses_str)
        data.insert(0, 'ID', sub)

        # Append to the list
        all_data.append(data)

# Concatenate all DataFrames into one
ceres_df = pd.concat(all_data, ignore_index=True)

# Merge with age and sex
ceres_df= ceres_df.merge(subjects, on="ID", how="left")

# Sort columns
ceres_df = ceres_df[finalColumns]

# Save it
if save :
    ceres_df.to_csv(ceres+'ceres_all_volumes_cm3_ALLGOODDATA.csv', index=False)

ceres_df

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,1366.2293,8.619207,8.284889,9.3166,9.6142,13.7456,...,4.4173,3.9308,6.0729,5.7547,4.6002,4.8214,4.2762,4.5613,0.67754,0.76646
1,sub-0025428,04,28,F,1369.8166,8.507694,8.410795,9.1906,9.7826,13.6649,...,4.7743,4.0400,5.7368,5.9833,4.6621,5.0157,4.1485,4.4919,0.68959,0.75048
2,sub-0025428,05,28,F,1360.8444,8.616637,8.130018,9.2284,9.9946,14.3354,...,4.4075,4.1506,6.1967,6.0598,4.4616,4.8385,4.2582,4.4872,0.66957,0.72811
3,sub-0025428,06,28,F,1365.8614,8.680817,8.318745,9.0717,9.8676,14.1545,...,4.4138,4.0671,5.8964,5.7238,4.5436,4.7273,4.2589,4.4558,0.67269,0.73244
4,sub-0025428,07,28,F,1358.9255,8.588919,8.133727,9.2548,10.4579,14.1116,...,4.5217,3.7899,5.7679,5.7123,4.2941,4.4990,4.0833,4.3073,0.71641,0.74861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,sub-0025456,01,22,F,1523.7960,7.772270,6.967920,8.6642,8.6257,11.0380,...,3.7664,4.3434,6.2302,6.3443,4.7122,5.1542,4.1738,3.9986,0.61876,0.63885
91,sub-0025456,02,22,F,1537.7596,7.653840,7.172650,8.5822,8.7061,10.9037,...,3.5361,4.0566,7.0184,6.0738,4.7279,5.1692,4.1357,3.9048,0.57019,0.66970
92,sub-0025456,03,22,F,1528.1232,7.681240,7.299910,8.5155,8.5782,11.0126,...,3.6589,4.0402,6.8331,6.1675,4.7596,4.8109,4.1176,3.9204,0.56868,0.60941
93,sub-0025456,04,22,F,1535.8441,7.705260,7.338610,8.7215,8.7255,11.3540,...,3.5469,4.1229,7.1043,6.1286,4.5017,4.9815,4.0906,3.9767,0.60502,0.64622
94,sub-0025456,05,22,F,1524.7560,7.775860,7.363910,8.4705,8.8126,11.0169,...,4.5300,4.1533,5.7048,6.3866,4.4513,4.7492,4.2208,3.9325,0.58783,0.67536

In [19]:
# Scale data
scaler = MinMaxScaler()

# Divide by ICV and scale
ceres_scaled = ceres_df.copy()
ceres_scaled.iloc[:,4:] = scaler.fit_transform(ceres_scaled.iloc[:,4:].div(ceres_scaled.ICV, axis=0))

# Save the dataframe
if save :
    ceres_scaled.to_csv(ceres+'ceres_all_volumes_cm3_scaled_ALLGOODDATA.csv', index=False)

ceres_scaled

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,0.0,0.801927,0.898450,0.934881,0.813882,0.885985,...,0.624328,0.304815,0.483914,0.527223,0.631378,0.590609,1.000000,1.000000,0.842418,1.000000
1,sub-0025428,04,28,F,0.0,0.766023,0.929267,0.898523,0.843411,0.865443,...,0.792933,0.341593,0.357270,0.592296,0.652170,0.644908,0.929460,0.963135,0.880206,0.939055
2,sub-0025428,05,28,F,0.0,0.810387,0.862050,0.922359,0.900735,1.000000,...,0.628067,0.392909,0.537410,0.627792,0.580772,0.601473,0.999414,0.974408,0.822793,0.879543
3,sub-0025428,06,28,F,0.0,0.819088,0.909159,0.876140,0.866839,0.958767,...,0.623197,0.356054,0.420826,0.518251,0.608208,0.562786,0.991777,0.952626,0.825197,0.885134
4,sub-0025428,07,28,F,0.0,0.806187,0.866576,0.931959,1.000000,0.963905,...,0.687318,0.259866,0.385087,0.523648,0.512955,0.501225,0.912971,0.895147,1.000000,0.953044
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,sub-0025456,01,22,F,0.0,0.358973,0.294018,0.559766,0.424971,0.207220,...,0.115150,0.291194,0.308287,0.506922,0.474360,0.530614,0.728157,0.556618,0.389590,0.342272
91,sub-0025456,02,22,F,0.0,0.313755,0.331148,0.525025,0.425221,0.170331,...,0.000000,0.182982,0.542571,0.417691,0.464144,0.522031,0.693625,0.503979,0.211833,0.417692
92,sub-0025456,03,22,F,0.0,0.331837,0.376823,0.522227,0.411659,0.198274,...,0.063430,0.185989,0.497000,0.453693,0.487086,0.434698,0.697183,0.520251,0.218637,0.247374
93,sub-0025456,04,22,F,0.0,0.328306,0.377302,0.557351,0.430785,0.243102,...,0.006620,0.206652,0.572937,0.434646,0.382140,0.473703,0.675534,0.534995,0.328451,0.349278
94,sub-0025456,05,22,F,0.0,0.358659,0.398110,0.516531,0.458600,0.202787,...,0.448978,0.226757,0.137219,0.517411,0.375429,0.420974,0.748397,0.528691,0.286073,0.452149

# DeepCERES

In [20]:
# Get subjects list and information
subjects = pd.read_csv(sub_fold+'subjects_DeepCeres.csv')
subjects_list = subjects['ID'].tolist()

print(subjects_list)
subjects

['sub-0025428', 'sub-0025432', 'sub-0025434', 'sub-0025435', 'sub-0025440', 'sub-0025445', 'sub-0025446', 'sub-0025447', 'sub-0025448', 'sub-0025449', 'sub-0025450', 'sub-0025455', 'sub-0025439', 'sub-0025441', 'sub-0025442', 'sub-0025443', 'sub-0025444', 'sub-0025452', 'sub-0025453', 'sub-0025454', 'sub-0025456']

             ID  age sex   good_ses
0   sub-0025428   28   F  2;4;5;6;7
1   sub-0025432   21   M  1;3;4;5;6
2   sub-0025434   24   M  3;5;7;8;9
3   sub-0025435   30   F  1;2;3;4;5
4   sub-0025440   24   M  1;2;3;4;5
5   sub-0025445   23   F  1;2;4;5;6
6   sub-0025446   30   M  1;2;3;4;5
7   sub-0025447   26   M  1;2;3;4;5
8   sub-0025448   23   M  1;2;3;5;6
9   sub-0025449   22   M  2;3;4;5;6
10  sub-0025450   25   F  1;2;3;4;5
11  sub-0025455   25   M  1;2;3;4;5
12  sub-0025439   24   F  2;3;4;6;7
13  sub-0025441   24   F  1;2;3;4;5
14  sub-0025442   27   F  1;2;3;4;5
15  sub-0025443   25   M  1;3;4;5;6
16  sub-0025444   27   F  1;2;3;4;6
17  sub-0025452   22   F  1;2;3;4;5
18  sub-0025453   26   F  1;3;4;5;6
19  sub-0025454   26   M  1;2;3;4;5
20  sub-0025456   22   F  1;2;3;4;5

In [21]:
# Columns to keep and convert
col = {
    'ICV total volume cm3':'ICV',
    'Lobules I-II right volume cm3':'Right.I.II',
    'Lobules I-II left volume cm3':'Left.I.II',
    'Lobule III right volume cm3':'Right.III',
    'Lobule III left volume cm3':'Left.III',
    'Lobule IV right volume cm3':'Right.IV',
    'Lobule IV left volume cm3':'Left.IV',
    'Lobule V right volume cm3':'Right.V',
    'Lobule V left volume cm3':'Left.V',
    'Lobule VI right volume cm3':'Right.VI',
    'Lobule VI left volume cm3':'Left.VI',
    'Crus I right volume cm3':'Right.Crus.I',
    'Crus I left volume cm3':'Left.Crus.I',
    'Crus II right volume cm3':'Right.Crus.II',
    'Crus II left volume cm3':'Left.Crus.II',
    'Lobule VIIB right volume cm3':'Right.VIIB',
    'Lobule VIIB left volume cm3':'Left.VIIB',
    'Lobule VIIIA right volume cm3':'Right.VIIIA',
    'Lobule VIIIA left volume cm3':'Left.VIIIA',
    'Lobule VIIIB right volume cm3':'Right.VIIIB',
    'Lobule VIIIB left volume cm3':'Left.VIIIB',
    'Lobule IX right volume cm3':'Right.IX',
    'Lobule IX left volume cm3':'Left.IX',
    'Lobule X right volume cm3':'Right.X',
    'Lobule X left volume cm3':'Left.X',
}

In [22]:
# List to store DataFrames
all_data = []

# Loop through subjects and sessions
for sub in subjects_list:
    sessions = subjects[subjects['ID']==sub]['good_ses'].iloc[0].split(';')
    for ses in sessions:
        ses_str = f"{int(ses):02d}"
        
        # Get the matching file (for given subject and given session)
        dataFile = glob.glob(os.path.join(deepCeres, 'output', f"{sub}_ses-{ses_str}_T1w_job*_archive", "report_job*.csv"))[0]

        # Read CSV
        data = pd.read_csv(dataFile, sep=';')

        # Keep only the columns in col and rename them
        data = data[list(col.keys())].rename(columns=col)

        # Group I.II, III, IV and V into I.V
        data.insert(4, "Left.I.V", data["Left.I.II"] + data["Left.III"] + data["Left.IV"] + data["Left.V"])
        data.insert(4, "Right.I.V", data["Right.I.II"] + data["Right.III"] + data["Right.IV"] + data["Right.V"])
        data = data.drop(["Left.I.II", "Left.III", "Left.IV", "Left.V", "Right.I.II", "Right.III", "Right.IV", "Right.V"], axis = 1)

        # Add Subject ID and Session columns at the beginning
        data.insert(0, 'ses', ses_str)
        data.insert(0, 'ID', sub)

        # Append to the list
        all_data.append(data)

# Concatenate all DataFrames into one
deepCeres_df = pd.concat(all_data, ignore_index=True)

# Merge with age and sex
deepCeres_df= deepCeres_df.merge(subjects, on="ID", how="left")

# Sort columns
deepCeres_df = deepCeres_df[finalColumns]

# Save it
if save :
    deepCeres_df.to_csv(deepCeres+'deepCeres_all_volumes_cm3_ALLGOODDATA.csv', index=False)

deepCeres_df

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,1351.732163,4.844692,5.276966,7.886563,7.846398,10.797028,...,3.567770,4.070928,4.578120,5.000307,2.880662,3.242694,3.261492,3.021514,0.666475,0.618700
1,sub-0025428,04,28,F,1356.510079,4.818477,5.325366,8.020314,7.860640,11.267158,...,3.643464,4.126064,4.510401,5.122244,2.848390,3.217787,3.169573,2.979283,0.570411,0.569861
2,sub-0025428,05,28,F,1353.522653,4.743133,5.256121,7.954060,7.767444,11.154665,...,3.610375,4.000871,4.630597,4.910384,2.731005,3.175029,3.135751,3.005220,0.544502,0.555007
3,sub-0025428,06,28,F,1356.212790,4.787504,5.296738,8.009532,7.717831,11.062090,...,3.526227,3.926097,4.524477,4.931424,2.692483,3.078751,3.038222,2.890901,0.563182,0.525226
4,sub-0025428,07,28,F,1349.206081,4.636417,5.406824,8.077539,7.843083,11.291785,...,3.508983,4.066855,4.551019,4.952618,2.949011,3.299096,3.163647,3.089757,0.601073,0.607284
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,sub-0025456,01,22,F,1507.794499,4.744360,5.554100,6.504078,6.640695,8.515099,...,3.536439,3.810678,4.740738,4.114696,3.319241,3.305459,2.772976,2.922469,0.580369,0.537815
101,sub-0025456,02,22,F,1507.685898,4.765246,5.437060,6.404089,6.682786,8.618859,...,3.381128,3.815138,4.832427,4.165247,3.320896,3.351314,2.959607,2.762495,0.582776,0.531005
102,sub-0025456,03,22,F,1513.339647,4.762292,5.534021,6.475115,6.726941,8.361339,...,3.368921,3.850469,4.668526,4.320713,3.288579,3.359837,2.891511,2.823886,0.554825,0.515058
103,sub-0025456,04,22,F,1513.348602,4.945554,5.492338,6.439130,6.789943,8.444711,...,3.423046,3.798759,4.601697,4.170641,3.437764,3.276169,2.913057,2.855294,0.587007,0.530252
104,sub-0025456,05,22,F,1499.761087,4.846415,5.505479,6.478014,6.730056,8.712867,...,3.511827,3.940128,4.576306,4.373247,3.366283,3.291503,2.820442,2.803579,0.598537,0.515025

In [23]:
# Scale data
scaler = MinMaxScaler()

# Divide by ICV and scale
deepCeres_scaled = deepCeres_df.copy()
deepCeres_scaled.iloc[:, 4:] = scaler.fit_transform(deepCeres_scaled.iloc[:, 4:].div(deepCeres_scaled.ICV, axis=0))

# Save the dataframe
if save :
    deepCeres_scaled.to_csv(deepCeres+'deepCeres_all_volumes_cm3_scaled_ALLGOODDATA.csv', index=False)

deepCeres_scaled

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,0.0,0.785214,0.810423,0.934871,0.996147,0.905701,...,0.364094,0.748719,0.641275,0.890336,0.774824,0.805311,1.000000,0.955676,1.000000,1.000000
1,sub-0025428,04,28,F,0.0,0.757235,0.824606,0.968210,0.991589,0.984380,...,0.405065,0.772740,0.611220,0.930977,0.747902,0.780285,0.935862,0.924109,0.643744,0.818567
2,sub-0025428,05,28,F,0.0,0.715354,0.797123,0.952875,0.965903,0.968375,...,0.388750,0.704142,0.657937,0.852620,0.677288,0.755685,0.919183,0.943541,0.554309,0.770104
3,sub-0025428,06,28,F,0.0,0.737917,0.811511,0.965368,0.943927,0.947470,...,0.329423,0.655363,0.616618,0.857018,0.649411,0.685077,0.854836,0.871756,0.618021,0.660264
4,sub-0025428,07,28,F,0.0,0.655906,0.877396,1.000000,1.000000,1.000000,...,0.330059,0.750814,0.634596,0.875309,0.821832,0.848525,0.942806,1.000000,0.766510,0.963321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,sub-0025456,01,22,F,0.0,0.402078,0.667975,0.285255,0.354514,0.327497,...,0.105098,0.361415,0.523340,0.377322,0.835295,0.612398,0.517468,0.715267,0.469006,0.512744
101,sub-0025456,02,22,F,0.0,0.414409,0.617942,0.257059,0.367450,0.344601,...,0.014488,0.363926,0.553002,0.395154,0.836375,0.640935,0.621689,0.629505,0.476980,0.491082
102,sub-0025456,03,22,F,0.0,0.402359,0.650665,0.270328,0.373231,0.297280,...,0.000000,0.375036,0.494555,0.444016,0.810927,0.638440,0.577676,0.656797,0.379199,0.433908
103,sub-0025456,04,22,F,0.0,0.508390,0.632838,0.260160,0.392292,0.310884,...,0.031499,0.347699,0.473088,0.391573,0.895715,0.586821,0.589641,0.673585,0.483605,0.482324
104,sub-0025456,05,22,F,0.0,0.476430,0.659769,0.287701,0.392621,0.367552,...,0.101708,0.441265,0.478248,0.476205,0.872419,0.614673,0.552372,0.659512,0.538612,0.448665