In [ ]:
import glob
import os
import pandas as pd
from sklearn.preprocessing import MinMaxScaler


### PATH

path = "reliability-cerebellar-volumetry/"
output = path + "outputs/"

# Where the subjects.csv file is
sub_fold = path + 'data/'


deepCeres = output + "deepCeres/"

acapulco = output + "acapulco3/"

suit = output + "suit/"

ceres = output + "ceres/"

# True if you want to save the csv files
save = False

In [2]:
# Get subjects list and information
subjects = pd.read_csv(sub_fold+'subjects.csv')
subjects_list = subjects['ID'].tolist()

print(subjects_list)
subjects

['sub-0025428', 'sub-0025432', 'sub-0025434', 'sub-0025435', 'sub-0025440', 'sub-0025445', 'sub-0025446', 'sub-0025447', 'sub-0025448', 'sub-0025449', 'sub-0025450', 'sub-0025455']

             ID  age sex   good_ses
0   sub-0025428   28   F  2;4;5;6;7
1   sub-0025432   21   M  1;3;4;5;6
2   sub-0025434   24   M  3;5;7;8;9
3   sub-0025435   30   F  1;2;3;4;5
4   sub-0025440   24   M  1;2;3;4;5
5   sub-0025445   23   F  1;2;4;5;6
6   sub-0025446   30   M  1;2;3;4;5
7   sub-0025447   26   M  1;2;3;4;5
8   sub-0025448   23   M  1;2;3;5;6
9   sub-0025449   22   M  2;3;4;5;6
10  sub-0025450   25   F  1;2;3;4;5
11  sub-0025455   25   M  1;2;3;4;5

In [3]:
# Columns order
finalColumns = ['ID', 'ses', 'age', 'sex', 'ICV', 'Left.I.V', 'Right.I.V',
       'Left.VI', 'Right.VI',
       'Left.Crus.I', 'Right.Crus.I', 'Left.Crus.II', 'Right.Crus.II',
       'Left.VIIB', 'Right.VIIB', 'Left.VIIIA', 'Right.VIIIA', 'Left.VIIIB',
       'Right.VIIIB', 'Left.IX', 'Right.IX', 'Left.X', 'Right.X']

In [4]:
# Get sessions to use
def is_good_session(row):
    good_list = row["good_ses"].split(";")
    good_list = [f"{int(s):02d}" for s in good_list]
    return row["ses"] in good_list

# ACAPULCO

In [5]:
# Columns to keep and convert
col = {
    'eTIV':'ICV',
    'Total_Cerebel_Vol':'Total_Cereb',
    'Rigt.IV' : 'Right.IV' # Error in ACAPULCO's outputs
}

# Column to drop
col_drop = ['Total_Cereb', 'Background', 'Corpus.Medullare', 'Vermis.IX', 'Vermis.VI', 'Vermis.VII', 'Vermis.VIII', 'Vermis.X']

In [6]:
# List to store DataFrames
all_data = []

# Loop through sessions
for ses in range(1, 11):
    ses_str = f"{ses:02d}"

    # Read CSV for given session
    data = pd.read_csv(acapulco + 'Cerebel_vols_ses-' + ses_str + '.csv', index_col=0)

    # Keep chosen subjects
    data = data[data["ID"].isin(subjects_list)].reset_index(drop=True)

    # Rename the columns in col and drop col_drop
    data = data.rename(columns=col)
    data = data.drop(col_drop, axis=1)

    # Group I.III, IV and V into I.V
    data.insert(4, "Left.I.V", data["Left.I.III"] + data["Left.IV"] + data["Left.V"])
    data.insert(4, "Right.I.V", data["Right.I.III"] + data["Right.IV"] + data["Right.V"])
    data = data.drop(["Left.I.III", "Left.IV", "Left.V", "Right.I.III", "Right.IV", "Right.V"], axis = 1)

    # Add Session column at the beginning
    data.insert(1, 'ses', ses_str)

    # Append to the list
    all_data.append(data)

# Concatenate all DataFrames into one
acapulco_df = pd.concat(all_data, ignore_index=True)

# Sort given id and session
acapulco_df = acapulco_df.sort_values(by=["ID", "ses"], ascending=[True, True]).reset_index(drop=True)

# Merge with age and sex
acapulco_df= acapulco_df.merge(subjects, on="ID", how="left")

# Keep only good sessions
acapulco_df = acapulco_df[acapulco_df.apply(is_good_session, axis=1)].reset_index(drop=True)

# Sort columns
acapulco_df = acapulco_df[finalColumns]

for i in range(4,acapulco_df.shape[1]):
    acapulco_df.isetitem(i, acapulco_df.iloc[:,i].astype(float))

# Save it
if save :
    acapulco_df.to_csv(acapulco+'acapulco3_all_volumes_cm3.csv', index=False)

acapulco_df

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,1.370856e+06,9313.0,8026.0,9231.0,10486.0,12131.0,...,6539.0,7407.0,5408.0,4279.0,2008.0,2247.0,3833.0,3315.0,386.0,498.0
1,sub-0025428,04,28,F,1.388105e+06,9392.0,7642.0,9471.0,10498.0,12199.0,...,6662.0,7111.0,5751.0,4940.0,2015.0,2215.0,3435.0,3102.0,397.0,460.0
2,sub-0025428,05,28,F,1.382804e+06,9337.0,7851.0,9423.0,10656.0,12833.0,...,6732.0,7335.0,5057.0,4733.0,2163.0,2509.0,3681.0,3197.0,374.0,490.0
3,sub-0025428,06,28,F,1.394185e+06,9784.0,7659.0,8945.0,10623.0,12135.0,...,6331.0,7412.0,5683.0,4809.0,2378.0,2152.0,3685.0,3460.0,373.0,482.0
4,sub-0025428,07,28,F,1.378490e+06,9375.0,7910.0,9090.0,10384.0,12045.0,...,6257.0,6990.0,5180.0,5151.0,1446.0,2382.0,3325.0,2716.0,398.0,445.0
5,sub-0025432,01,21,M,1.404656e+06,7797.0,7559.0,8812.0,9040.0,10637.0,...,5877.0,7930.0,5547.0,6059.0,3199.0,2651.0,2425.0,2484.0,414.0,455.0
6,sub-0025432,03,21,M,1.421069e+06,7984.0,8305.0,8673.0,9149.0,10463.0,...,6779.0,8326.0,5079.0,5871.0,3273.0,2786.0,2575.0,2880.0,423.0,496.0
7,sub-0025432,04,21,M,1.442737e+06,7709.0,7874.0,8679.0,9123.0,11100.0,...,6480.0,8504.0,5788.0,5540.0,3028.0,2480.0,2388.0,2677.0,430.0,439.0
8,sub-0025432,05,21,M,1.416419e+06,7998.0,7594.0,8854.0,8822.0,11161.0,...,6181.0,7809.0,5407.0,6059.0,2714.0,2529.0,2684.0,2748.0,407.0,459.0
9,sub-0025432,06,21,M,1.424534e+06,7774.0,8026.0,8494.0,8445.0,10594.0,...,6498.0,8570.0,5055.0,6008.0,3008.0,2692.0,2503.0,2582.0,433.0,496.0
10,sub-0025434,03,24,M,1.332421e+06,7543.0,7522.0,7530.0,7354.0,10233.0,...,5020.0,4955.0,4968.0,4962.0,3870.0,3027.0,2318.0,2305.0,346.0,365.0
11,sub-0025434,05,24,M,1.339030e+06,7438.0,7304.0,7467.0,7563.0,10442.0,...,4813.0,4396.0,5194.0,5027.0,3554.0,2783.0,2231.0,2043.0,321.0,238.0
12,sub-0025434,07,24,M,1.312875e+06,8034.0,7493.0,7402.0,7827.0,10266.0,...,5248.0,4904.0,4406.0,5336.0,3784.0,3168.0,2250.0,2283.0,374.0,325.0
13,sub-0025434,08,24,M,1.326740e+06,7714.0,7209.0,7371.0,7965.0,9950.0,...,4920.0,4961.0,4730.0,4873.0,3817.0,2870.0,2204.0,2316.0,380.0,346.0
14,sub-0025434,09,24,M,1.333862e+06,7887.0,7072.0,7412.0,8008.0,10140.0,...,4907.0,4931.0,5352.0,4958.0,3578.0,2998.0,2294.0,2382.0,373.0,337.0
15,sub-0025435,01,30,F,1.353405e+06,6552.0,7352.0,6536.0,6838.0,10304.0,...,4706.0,4766.0,3916.0,4333.0,2739.0,2707.0,2424.0,2418.0,301.0,235.0
16,sub-0025435,02,30,F,1.345798e+06,6696.0,7063.0,6683.0,6999.0,10942.0,...,4925.0,4757.0,4210.0,4573.0,2753.0,2870.0,2498.0,2460.0,270.0,277.0
17,sub-0025435,03,30,F,1.348957e+06,6750.0,7115.0,6693.0,7121.0,10622.0,...,5065.0,4981.0,4055.0,4663.0,2688.0,2721.0,2415.0,2447.0,314.0,303.0
18,sub-0025435,04,30,F,1.355278e+06,6675.0,7500.0,6727.0,6849.0,10250.0,...,4530.0,4519.0,4662.0,4354.0,2859.0,2988.0,2459.0,2509.0,321.0,311.0
19,sub-0025435,05,30,F,1.354093e+06,6697.0,7243.0,6715.0,6757.0,10704.0,...,4788.0,4609.0,4541.0,4394.0,3121.0,2899.0,2572.0,2478.0,315.0,335.0
20,sub-0025440,01,24,M,1.412080e+06,6986.0,7388.0,7525.0,7985.0,11274.0,...,5231.0,5300.0,4508.0,4557.0,3248.0,3383.0,3032.0,3019.0,415.0,406.0
21,sub-0025440,02,24,M,1.406342e+06,7075.0,7339.0,7607.0,8180.0,11211.0,...,4933.0,5114.0,4353.0,4789.0,3292.0,3207.0,2898.0,2781.0,363.0,354.0
22,sub-0025440,03,24,M,1.383582e+06,7376.0,7393.0,7329.0,8575.0,11120.0,...,4845.0,5310.0,4501.0,4657.0,2844.0,2885.0,2727.0,2920.0,407.0,433.0
23,sub-0025440,04,24,M,1.420990e+06,7273.0,7460.0,7324.0,8135.0,11555.0,...,5022.0,5594.0,4703.0,4786.0,3224.0,3068.0,3071.0,2858.0,334.0,395.0
24,sub-0025440,05,24,M,1.403503e+06,7029.0,7355.0,7622.0,8183.0,11483.0,...,4563.0,5646.0,4427.0,4099.0,3032.0,2785.0,2758.0,2883.0,409.0,433.0
25,sub-0025445,01,23,F,1.464986e+06,8378.0,7926.0,7999.0,7857.0,10785.0,...,5209.0,6036.0,4795.0,3759.0,2152.0,1724.0,2140.0,2146.0,370.0,304.0
26,sub-0025445,02,23,F,1.466683e+06,7778.0,8283.0,8029.0,8013.0,9541.0,...,5303.0,5692.0,4452.0,4286.0,2170.0,1271.0,1671.0,1938.0,378.0,354.0
27,sub-0025445,04,23,F,1.450042e+06,8041.0,8070.0,8275.0,8197.0,10075.0,...,5453.0,5482.0,4683.0,4406.0,2231.0,1684.0,1899.0,1603.0,333.0,320.0
28,sub-0025445,05,23,F,1.456292e+06,8984.0,8070.0,7439.0,8329.0,10875.0,...,5227.0,5653.0,4343.0,3765.0,2508.0,1632.0,1999.0,1955.0,321.0,313.0
29,sub-0025445,06,23,F,1.468118e+06,7872.0,8135.0,8237.0,7739.0,10188.0,...,5247.0,5822.0,4540.0,3995.0,2499.0,1489.0,2138.0,1928.0,339.0,335.0
30,sub-0025446,01,30,M,1.498093e+06,7577.0,6948.0,6917.0,7697.0,12650.0,...,5853.0,6681.0,4383.0,4558.0,2549.0,3643.0,2802.0,3090.0,462.0,440.0
31,sub-0025446,02,30,M,1.501302e+06,7092.0,6891.0,7845.0,7788.0,12039.0,...,5738.0,6399.0,4807.0,4203.0,2656.0,3481.0,2877.0,2848.0,373.0,486.0
32,sub-0025446,03,30,M,1.488073e+06,7030.0,6936.0,6800.0,7868.0,12663.0,...,5630.0,6037.0,4918.0,4269.0,3025.0,3585.0,2794.0,2835.0,485.0,537.0
33,sub-0025446,04,30,M,1.493331e+06,7313.0,7096.0,7891.0,7900.0,11515.0,...,5485.0,6070.0,4584.0,3963.0,3035.0,3603.0,2813.0,2881.0,407.0,495.0
34,sub-0025446,05,30,M,1.496265e+06,7353.0,7063.0,7720.0,7874.0,11736.0,...,5597.0,6711.0,4899.0,4207.0,3025.0,4054.0,3003.0,3049.0,468.0,538.0
35,sub-0025447,01,26,M,1.696789e+06,6885.0,6790.0,8309.0,9101.0,12795.0,...,5877.0,6398.0,4877.0,4772.0,1381.0,2921.0,2411.0,2258.0,581.0,512.0
36,sub-0025447,02,26,M,1.602568e+06,6402.0,6935.0,8419.0,8917.0,13027.0,...,5125.0,6072.0,4588.0,5598.0,1476.0,1960.0,2435.0,1867.0,542.0,553.0
37,sub-0025447,03,26,M,1.691454e+06,5950.0,6409.0,9081.0,9358.0,12844.0,...,5601.0,5976.0,4061.0,5734.0,1382.0,1898.0,2411.0,1976.0,485.0,552.0
38,sub-0025447,04,26,M,1.706511e+06,6498.0,6903.0,8569.0,8950.0,12716.0,...,5653.0,6095.0,4641.0,5192.0,1442.0,2508.0,2428.0,2033.0,614.0,579.0
39,sub-0025447,05,26,M,1.698021e+06,6481.0,6498.0,8790.0,9398.0,12844.0,...,5974.0,6395.0,5226.0,5409.0,1206.0,2193.0,2554.0,2105.0,546.0,579.0
40,sub-0025448,01,23,M,1.698270e+06,9043.0,9249.0,11641.0,10385.0,13524.0,...,7005.0,6716.0,7623.0,5665.0,3534.0,4897.0,3827.0,3512.0,404.0,446.0
41,sub-0025448,02,23,M,1.676777e+06,9111.0,9492.0,11436.0,10795.0,13980.0,...,6660.0,6934.0,7783.0,5678.0,3371.0,4439.0,3713.0,3401.0,422.0,450.0
42,sub-0025448,03,23,M,1.697903e+06,9383.0,9427.0,11396.0,10587.0,13701.0,...,7036.0,6787.0,7755.0,5589.0,3651.0,4651.0,3758.0,3565.0,372.0,452.0
43,sub-0025448,05,23,M,1.688358e+06,9295.0,9323.0,11579.0,10624.0,13856.0,...,7323.0,6796.0,7080.0,5540.0,3687.0,4940.0,3675.0,3450.0,439.0,423.0
44,sub-0025448,06,23,M,1.685445e+06,9357.0,9667.0,11393.0,10229.0,13945.0,...,6935.0,6640.0,7816.0,5270.0,3524.0,4996.0,3942.0,3640.0,427.0,445.0
45,sub-0025449,02,22,M,1.752653e+06,8607.0,8915.0,10065.0,10374.0,14645.0,...,8217.0,6638.0,5663.0,5976.0,2530.0,4256.0,3570.0,3250.0,473.0,363.0
46,sub-0025449,03,22,M,1.751481e+06,8889.0,8936.0,10378.0,10343.0,14617.0,...,7622.0,6710.0,5960.0,5765.0,3812.0,4033.0,3585.0,3282.0,469.0,384.0
47,sub-0025449,04,22,M,1.757391e+06,8604.0,9022.0,10252.0,9989.0,14804.0,...,7865.0,6824.0,6047.0,5256.0,2524.0,3691.0,3471.0,3305.0,428.0,329.0
48,sub-0025449,05,22,M,1.745821e+06,8584.0,9058.0,9994.0,10060.0,15012.0,...,8295.0,7116.0,5597.0,5157.0,2780.0,3417.0,3638.0,3298.0,475.0,466.0
49,sub-0025449,06,22,M,1.755399e+06,8734.0,8763.0,10234.0,10089.0,14979.0,...,8057.0,6873.0,5247.0,5583.0,2695.0,3603.0,3627.0,3356.0,429.0,421.0
50,sub-0025450,01,25,F,1.366127e+06,6607.0,6603.0,7769.0,7876.0,9683.0,...,5760.0,5263.0,4068.0,4530.0,2826.0,2569.0,2475.0,2458.0,348.0,308.0
51,sub-0025450,02,25,F,1.361626e+06,6902.0,6680.0,7337.0,7960.0,9517.0,...,5552.0,6139.0,4711.0,4017.0,2642.0,2792.0,2431.0,2526.0,263.0,350.0
52,sub-0025450,03,25,F,1.359818e+06,6713.0,6684.0,7369.0,8106.0,9520.0,...,5307.0,6026.0,4317.0,4156.0,2800.0,2203.0,2404.0,2551.0,311.0,346.0
53,sub-0025450,04,25,F,1.363799e+06,6412.0,6494.0,7470.0,7941.0,9396.0,...,5714.0,5925.0,4397.0,4258.0,2479.0,2489.0,2427.0,2481.0,306.0,315.0
54,sub-0025450,05,25,F,1.358742e+06,6768.0,6673.0,7408.0,7812.0,9467.0,...,5216.0,5815.0,4035.0,3941.0,3222.0,2229.0,2296.0,2475.0,315.0,360.0
55,sub-0025455,01,25,M,1.553103e+06,7149.0,6425.0,9115.0,9112.0,10424.0,...,4569.0,5575.0,4879.0,4032.0,3217.0,2919.0,3199.0,2977.0,430.0,412.0
56,sub-0025455,02,25,M,1.558955e+06,7338.0,6779.0,8720.0,8781.0,10717.0,...,5808.0,6132.0,5728.0,4915.0,3031.0,3108.0,3153.0,3066.0,406.0,422.0
57,sub-0025455,03,25,M,1.550227e+06,7034.0,6528.0,9029.0,9241.0,10268.0,...,5680.0,5831.0,5842.0,5026.0,2292.0,2945.0,3185.0,2927.0,385.0,404.0
58,sub-0025455,04,25,M,1.540075e+06,7030.0,6338.0,9287.0,9056.0,10247.0,...,6254.0,5878.0,5057.0,4691.0,2195.0,2923.0,3157.0,3024.0,368.0,392.0
59,sub-0025455,05,25,M,1.551094e+06,7362.0,6696.0,8464.0,8563.0,10619.0,...,5812.0,5764.0,5519.0,4598.0,2458.0,3154.0,3109.0,3095.0,362.0,423.0

In [7]:
# Scale data
scaler = MinMaxScaler()

# Divide by ICV and scale
acapulco_scaled = acapulco_df.copy()
acapulco_scaled.iloc[:, 4:] = scaler.fit_transform(acapulco_scaled.iloc[:, 4:].div(acapulco_scaled.ICV, axis=0))

# Save
if save :
    acapulco_scaled.to_csv(acapulco+'acapulco3_all_volumes_cm3_scaled.csv', index=False)

acapulco_scaled

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,0.0,0.935958,1.000000,0.945645,0.979072,0.844628,...,0.948947,0.775777,0.689094,0.317869,0.343872,0.368294,1.000000,0.953832,0.530610,1.000000
1,sub-0025428,04,28,F,0.0,0.928098,0.830860,0.984632,0.947257,0.822656,...,0.964174,0.673186,0.777492,0.568153,0.337874,0.347593,0.805966,0.820502,0.557166,0.831841
2,sub-0025428,05,28,F,0.0,0.924144,0.914244,0.980892,1.000000,1.000000,...,1.000000,0.739642,0.560602,0.490302,0.389187,0.451868,0.919069,0.876645,0.463935,0.952940
3,sub-0025428,06,28,F,0.0,1.000000,0.825140,0.806767,0.968124,0.792305,...,0.830074,0.744007,0.747661,0.505506,0.453648,0.322733,0.907685,1.000000,0.446383,0.907429
4,sub-0025428,07,28,F,0.0,0.938058,0.943565,0.884652,0.936230,0.804488,...,0.829047,0.654143,0.605530,0.669942,0.154374,0.410654,0.768219,0.628364,0.573489,0.786650
5,sub-0025432,01,21,M,0.0,0.580892,0.770852,0.744494,0.532279,0.384654,...,0.644734,0.864439,0.690892,1.000000,0.714225,0.486605,0.354364,0.481685,0.609568,0.792481
6,sub-0025432,03,21,M,0.0,0.600172,0.994894,0.670090,0.533152,0.309019,...,0.949123,0.942542,0.523564,0.895792,0.725969,0.521502,0.406040,0.669324,0.627145,0.924890
7,sub-0025432,04,21,M,0.0,0.521604,0.807785,0.631854,0.490917,0.428267,...,0.804359,0.955488,0.718922,0.729009,0.632813,0.406352,0.311380,0.544970,0.629433,0.688917
8,sub-0025432,05,21,M,0.0,0.608266,0.761179,0.734685,0.455934,0.495295,...,0.738104,0.816027,0.632145,0.979502,0.549555,0.438071,0.456080,0.606444,0.565224,0.793187
9,sub-0025432,06,21,M,0.0,0.554149,0.893201,0.608696,0.345431,0.335703,...,0.840710,1.000000,0.512166,0.945073,0.638637,0.487771,0.372873,0.513742,0.664924,0.920414
10,sub-0025434,03,24,M,0.0,0.612406,0.898642,0.472673,0.194852,0.423330,...,0.428611,0.159465,0.592506,0.662705,1.000000,0.669913,0.362385,0.453732,0.399205,0.528902
11,sub-0025434,05,24,M,0.0,0.582018,0.806338,0.439924,0.242288,0.465911,...,0.338715,0.000000,0.659615,0.679963,0.885916,0.577696,0.317985,0.305355,0.279479,0.021643
12,sub-0025434,07,24,M,0.0,0.743338,0.928635,0.466834,0.357754,0.473585,...,0.547870,0.165509,0.426241,0.857434,0.989853,0.737237,0.346755,0.460269,0.550382,0.389748
13,sub-0025434,08,24,M,0.0,0.656155,0.796136,0.430878,0.373111,0.358318,...,0.397860,0.166945,0.519574,0.633444,0.987462,0.618136,0.315018,0.465138,0.559655,0.459571
14,sub-0025434,09,24,M,0.0,0.684343,0.732371,0.431349,0.373180,0.395218,...,0.382525,0.151412,0.719186,0.658687,0.898803,0.658378,0.350391,0.494319,0.518988,0.416650
15,sub-0025435,01,30,F,0.0,0.378122,0.795461,0.113452,0.022969,0.399326,...,0.277861,0.087271,0.219815,0.363729,0.598631,0.540402,0.393378,0.494909,0.175524,0.000000
16,sub-0025435,02,30,F,0.0,0.416512,0.706370,0.173111,0.077531,0.585652,...,0.372531,0.092108,0.324607,0.476128,0.608586,0.603533,0.432678,0.524924,0.044844,0.169741
17,sub-0025435,03,30,F,0.0,0.424619,0.719080,0.171268,0.106345,0.493314,...,0.421953,0.149837,0.270058,0.509751,0.584442,0.548494,0.392915,0.514811,0.237754,0.268834
18,sub-0025435,04,30,F,0.0,0.402141,0.844693,0.172119,0.023388,0.381179,...,0.207959,0.018807,0.463681,0.370065,0.637709,0.637929,0.407472,0.541904,0.262233,0.294437
19,sub-0025435,05,30,F,0.0,0.408014,0.755157,0.170144,0.000000,0.504373,...,0.308377,0.044193,0.425145,0.388576,0.726729,0.607515,0.458800,0.526446,0.236888,0.388956
20,sub-0025440,01,24,M,0.0,0.408462,0.698533,0.331816,0.244742,0.532856,...,0.395851,0.172101,0.353258,0.378379,0.724583,0.729005,0.608346,0.750224,0.604520,0.600520
21,sub-0025440,02,24,M,0.0,0.432310,0.692000,0.366795,0.304288,0.528452,...,0.293706,0.129312,0.309884,0.480308,0.743118,0.674003,0.556122,0.633595,0.389836,0.411730
22,sub-0025440,03,24,M,0.0,0.518111,0.752450,0.317876,0.444630,0.552003,...,0.290643,0.203032,0.380345,0.457770,0.613101,0.580937,0.501983,0.730229,0.606147,0.734651
23,sub-0025440,04,24,M,0.0,0.457304,0.707179,0.255403,0.270552,0.586071,...,0.307448,0.239192,0.405566,0.459013,0.710312,0.616163,0.616785,0.658157,0.251405,0.550194
24,sub-0025440,05,24,M,0.0,0.425853,0.702627,0.376246,0.309406,0.604092,...,0.160548,0.270695,0.336208,0.202936,0.660850,0.532860,0.498429,0.689308,0.589643,0.711227
25,sub-0025445,01,23,F,0.0,0.628891,0.784843,0.389103,0.137383,0.308687,...,0.318613,0.306328,0.389234,0.000000,0.345775,0.147892,0.194029,0.261126,0.356506,0.178624
26,sub-0025445,02,23,F,0.0,0.510121,0.899646,0.395281,0.174260,0.000000,...,0.349745,0.218766,0.283177,0.203904,0.350594,0.000000,0.000000,0.156849,0.387484,0.357122
27,sub-0025445,04,23,F,0.0,0.579330,0.859911,0.496866,0.244064,0.159596,...,0.424979,0.182072,0.369818,0.270447,0.377504,0.140523,0.102798,0.000000,0.219009,0.248086
28,sub-0025445,05,23,F,0.0,0.757537,0.848347,0.235313,0.268504,0.346792,...,0.336047,0.219099,0.259439,0.011123,0.461180,0.121124,0.140852,0.172181,0.163647,0.217745
29,sub-0025445,06,23,F,0.0,0.526933,0.848172,0.454852,0.103578,0.156505,...,0.328111,0.249778,0.308603,0.088851,0.452064,0.070386,0.191326,0.150961,0.226566,0.287635
30,sub-0025446,01,30,M,0.0,0.440019,0.410928,0.020771,0.054421,0.698642,...,0.500964,0.430547,0.234219,0.272737,0.451753,0.746168,0.441267,0.695467,0.691526,0.633148
31,sub-0025446,02,30,M,0.0,0.344630,0.387748,0.286564,0.072695,0.545492,...,0.456868,0.358330,0.357467,0.133711,0.482576,0.692247,0.469007,0.575138,0.331837,0.791407
32,sub-0025446,03,30,M,0.0,0.344725,0.422142,0.000000,0.109469,0.722278,...,0.436833,0.283185,0.403460,0.173331,0.602754,0.735393,0.445624,0.581045,0.796735,0.987306
33,sub-0025446,04,30,M,0.0,0.394117,0.466064,0.312212,0.110503,0.434479,...,0.379516,0.286043,0.298451,0.050299,0.602543,0.737095,0.449312,0.598552,0.476418,0.832298
34,sub-0025446,05,30,M,0.0,0.399011,0.450877,0.257746,0.100287,0.482252,...,0.414632,0.439876,0.389718,0.140633,0.597681,0.878534,0.523728,0.677388,0.717849,0.980411
35,sub-0025447,01,26,M,0.0,0.154279,0.102934,0.142990,0.137556,0.373140,...,0.270825,0.178439,0.211251,0.141036,0.047238,0.407560,0.169979,0.163679,0.895667,0.675543
36,sub-0025447,02,26,M,0.0,0.136329,0.260631,0.298791,0.211390,0.585053,...,0.132955,0.185123,0.206187,0.530579,0.096062,0.169933,0.229443,0.043248,0.870438,0.904000
37,sub-0025447,03,26,M,0.0,0.000000,0.000000,0.349178,0.199726,0.392147,...,0.191796,0.091503,0.000000,0.471549,0.048677,0.121819,0.172683,0.045588,0.561571,0.805261
38,sub-0025447,04,26,M,0.0,0.082881,0.123953,0.197375,0.093726,0.340978,...,0.192448,0.105612,0.142225,0.272697,0.061415,0.287508,0.171105,0.062368,1.000000,0.873508
39,sub-0025447,05,26,M,0.0,0.085460,0.018280,0.265218,0.200522,0.381565,...,0.299172,0.176791,0.302045,0.354527,0.000000,0.202573,0.220188,0.097506,0.770487,0.882453
40,sub-0025448,01,23,M,0.0,0.516322,0.802193,0.998462,0.414204,0.525443,...,0.614027,0.245749,0.931738,0.440515,0.624679,0.961537,0.672496,0.699365,0.268458,0.469224
41,sub-0025448,02,23,M,0.0,0.547411,0.906144,0.983433,0.533092,0.660215,...,0.534672,0.311867,1.000000,0.469419,0.592534,0.848943,0.648895,0.670525,0.351173,0.499555
42,sub-0025448,03,23,M,0.0,0.573864,0.853514,0.936057,0.458495,0.563626,...,0.623967,0.261362,0.966866,0.415316,0.656289,0.892764,0.648261,0.722371,0.155673,0.488158
43,sub-0025448,05,23,M,0.0,0.567899,0.838889,1.000000,0.479542,0.613143,...,0.724363,0.271581,0.799968,0.409357,0.671546,0.981749,0.626141,0.681504,0.401234,0.405520
44,sub-0025448,06,23,M,0.0,0.581127,0.942314,0.956957,0.397259,0.637282,...,0.608761,0.240261,0.998084,0.320938,0.629192,1.000000,0.724030,0.765981,0.361207,0.476633
45,sub-0025449,02,22,M,0.0,0.398041,0.628132,0.512592,0.342033,0.666873,...,0.906542,0.184567,0.370505,0.482825,0.334186,0.744528,0.541784,0.544120,0.460405,0.176536
46,sub-0025449,03,22,M,0.0,0.444981,0.635584,0.592361,0.336975,0.663128,...,0.731836,0.200536,0.447146,0.415197,0.668204,0.684605,0.547777,0.558298,0.447785,0.240491
47,sub-0025449,04,22,M,0.0,0.393770,0.650968,0.552324,0.255497,0.691356,...,0.796013,0.219557,0.464131,0.243132,0.330856,0.588138,0.504468,0.563228,0.302384,0.071573
48,sub-0025449,05,22,M,0.0,0.399768,0.677421,0.504642,0.284341,0.754403,...,0.939257,0.290171,0.359276,0.222026,0.402022,0.519953,0.570106,0.569371,0.473617,0.491915
49,sub-0025449,06,22,M,0.0,0.416517,0.582363,0.550737,0.278848,0.730724,...,0.855424,0.231383,0.262489,0.351667,0.375994,0.565376,0.559461,0.585890,0.307461,0.349057
50,sub-0025450,01,25,F,0.0,0.376744,0.505558,0.488191,0.285399,0.209986,...,0.661530,0.208386,0.257445,0.429184,0.619065,0.483366,0.405844,0.504096,0.369544,0.273247
51,sub-0025450,02,25,F,0.0,0.443212,0.540668,0.357768,0.315128,0.174500,...,0.589471,0.448443,0.472583,0.219874,0.560597,0.564405,0.389954,0.544704,0.000000,0.439829
52,sub-0025450,03,25,F,0.0,0.405426,0.545249,0.371181,0.357521,0.178642,...,0.498763,0.420230,0.345329,0.280608,0.614725,0.359211,0.379402,0.559855,0.213359,0.426120
53,sub-0025450,04,25,F,0.0,0.338251,0.470860,0.396630,0.306569,0.138518,...,0.647757,0.388400,0.367372,0.318300,0.504718,0.456931,0.386467,0.518581,0.187353,0.302342
54,sub-0025450,05,25,F,0.0,0.418109,0.543214,0.385599,0.279592,0.166585,...,0.465603,0.364694,0.253828,0.191451,0.757012,0.368945,0.332271,0.520292,0.232111,0.481515
55,sub-0025455,01,25,M,0.0,0.310100,0.168386,0.567727,0.322865,0.074432,...,0.000000,0.112189,0.330497,0.017280,0.620303,0.482872,0.555568,0.589517,0.502341,0.483226
56,sub-0025455,02,25,M,0.0,0.339801,0.270795,0.447382,0.236582,0.133076,...,0.406807,0.237989,0.568275,0.335805,0.562385,0.537305,0.533091,0.625770,0.403724,0.511799
57,sub-0025455,03,25,M,0.0,0.291345,0.204265,0.548243,0.357510,0.042659,...,0.374835,0.175048,0.610325,0.386933,0.350122,0.492529,0.552423,0.568664,0.331235,0.458609
58,sub-0025455,04,25,M,0.0,0.299148,0.157980,0.638224,0.327750,0.053478,...,0.580836,0.195287,0.393937,0.274695,0.325859,0.491690,0.549624,0.623473,0.274820,0.426580
59,sub-0025455,05,25,M,0.0,0.351038,0.255559,0.387649,0.195345,0.122864,...,0.417946,0.158474,0.516452,0.228004,0.398519,0.556260,0.522156,0.646597,0.241422,0.522433

# SUIT

In [8]:
# Columns to keep and convert
col = {
    '1.0' : 'Left.I.IV',
    '2.0' : 'Right.I.IV',
    '3.0' : 'Left.V',
    '4.0' : 'Right.V',
    '5.0' : 'Left.VI',
    '6.0' : 'Vermis.VI',
    '7.0' : 'Right.VI',
    '8.0' : 'Left.Crus.I',
    '9.0' : 'Vermis.Crus.I',
    '10.0' : 'Right.Crus.I',
    '11.0' : 'Left.Crus.II',
    '12.0' : 'Vermis.Crus.II',
    '13.0' : 'Right.Crus.II',
    '14.0' : 'Left.VIIB',
    '15.0' : 'Vermis.VIIB',
    '16.0' : 'Right.VIIB',
    '17.0' : 'Left.VIIIA',
    '18.0' : 'Vermis.VIIIA',
    '19.0' : 'Right.VIIIA',
    '20.0' : 'Left.VIIIB',
    '21.0' : 'Vermis.VIIIB',
    '22.0' : 'Right.VIIIB',
    '23.0' : 'Left.IX',
    '24.0' : 'Vermis.IX',
    '25.0' : 'Right.IX',
    '26.0' : 'Left.X',
    '27.0' : 'Vermis.X',
    '28.0' : 'Right.X'
}

In [9]:
# List to store DataFrames
all_data = []

# Loop through subjects and sessions
for sub in subjects_list:
    sessions = subjects[subjects['ID']==sub]['good_ses'].iloc[0].split(';')
    for ses in sessions:
            ses_str = f"{int(ses):02d}"

            # Get the matching file (for given subject and given session)
            dataFile = os.path.join(suit, sub, f"ses-{ses_str}", f"{sub}_ses-{ses_str}_volumes.csv")

            # Read CSV
            data = pd.read_csv(dataFile)
            
            # Keep only the columns in col and rename them
            data = data[list(col.keys())].rename(columns=col)

            # Group I.III, IV and V into I.V
            data.insert(4, "Left.I.V", data["Left.I.IV"] + data["Left.V"])
            data.insert(4, "Right.I.V", data["Right.I.IV"] + data["Right.V"])
            data = data.drop(["Left.I.IV", "Left.V", "Right.I.IV", "Right.V"], axis = 1)

            # Add Subject ID and Session columns at the beginning
            data.insert(0, 'ses', ses_str)
            data.insert(0, 'ID', sub)

            # Append to the list
            all_data.append(data)

# Concatenate all DataFrames into one
suit_df = pd.concat(all_data, ignore_index=True)

# Add ICV from acapulco
suit_df.insert(4, 'ICV', acapulco_df['ICV'])

# Sort given id and session
suit_df = suit_df.sort_values(by=["ID", "ses"], ascending=[True, True]).reset_index(drop=True)

# Merge with age and sex
suit_df= suit_df.merge(subjects, on="ID", how="left")

# Sort columns
suit_df = suit_df[finalColumns]

# Save it
if save :
    suit_df.to_csv(suit+'suit_all_volumes_cm3.csv', index=False)

suit_df

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,1.370856e+06,1.208054,1.185940,0.676470,0.651703,0.655798,...,0.700961,0.669952,0.701355,0.672463,0.638406,0.608524,0.575977,0.621894,0.547930,0.528146
1,sub-0025428,04,28,F,1.388105e+06,1.199541,1.176284,0.677726,0.655497,0.660897,...,0.693731,0.655724,0.704053,0.676164,0.630693,0.611455,0.570927,0.615120,0.539170,0.512622
2,sub-0025428,05,28,F,1.382804e+06,1.181272,1.151466,0.674730,0.656717,0.664996,...,0.703607,0.681044,0.717994,0.678886,0.651621,0.605657,0.589995,0.609097,0.532673,0.490535
3,sub-0025428,06,28,F,1.394185e+06,1.198158,1.177947,0.682938,0.665247,0.666670,...,0.680542,0.669607,0.715784,0.680477,0.639928,0.603814,0.579066,0.612285,0.513464,0.519492
4,sub-0025428,07,28,F,1.378490e+06,1.196252,1.163871,0.678749,0.658918,0.664879,...,0.667896,0.643821,0.658613,0.675816,0.570722,0.604663,0.531652,0.590116,0.510917,0.484815
5,sub-0025432,01,21,M,1.404656e+06,1.201320,1.286299,0.705057,0.725984,0.701782,...,0.735597,0.776735,0.729037,0.741134,0.660714,0.673303,0.593445,0.623432,0.619262,0.546946
6,sub-0025432,03,21,M,1.421069e+06,1.218237,1.279630,0.699371,0.735307,0.684041,...,0.753775,0.788775,0.752311,0.781818,0.662579,0.703228,0.597989,0.645456,0.573430,0.589895
7,sub-0025432,04,21,M,1.442737e+06,1.214190,1.259060,0.700796,0.720499,0.719501,...,0.735957,0.750461,0.738304,0.760422,0.672834,0.681367,0.583735,0.626064,0.550284,0.479684
8,sub-0025432,05,21,M,1.416419e+06,1.221035,1.255955,0.699023,0.714380,0.706601,...,0.739318,0.759243,0.746267,0.732342,0.656051,0.675285,0.602666,0.622560,0.558096,0.559936
9,sub-0025432,06,21,M,1.424534e+06,1.223946,1.301130,0.685818,0.714595,0.703372,...,0.756243,0.767559,0.758334,0.747239,0.674632,0.665860,0.607058,0.643079,0.608379,0.600648
10,sub-0025434,03,24,M,1.332421e+06,1.063381,1.082619,0.593627,0.619935,0.593394,...,0.651358,0.643458,0.624976,0.647705,0.589078,0.605426,0.489605,0.550944,0.471394,0.446894
11,sub-0025434,05,24,M,1.339030e+06,1.067053,1.092162,0.588599,0.610546,0.590777,...,0.650263,0.630286,0.619684,0.631109,0.585171,0.588689,0.483683,0.547399,0.454750,0.446390
12,sub-0025434,07,24,M,1.312875e+06,1.061650,1.097507,0.602869,0.637393,0.588937,...,0.634105,0.648475,0.619909,0.654720,0.579151,0.613894,0.493397,0.546832,0.452498,0.451592
13,sub-0025434,08,24,M,1.326740e+06,1.064450,1.092552,0.592947,0.622726,0.591249,...,0.625974,0.639033,0.598460,0.640509,0.568213,0.608088,0.484688,0.553859,0.473288,0.438626
14,sub-0025434,09,24,M,1.333862e+06,1.064782,1.090595,0.598550,0.620895,0.589777,...,0.615431,0.635651,0.608727,0.632743,0.578082,0.600045,0.501083,0.553118,0.475424,0.435241
15,sub-0025435,01,30,F,1.353405e+06,0.962972,0.971177,0.542934,0.534652,0.563516,...,0.565004,0.611825,0.564658,0.572843,0.531816,0.513437,0.478530,0.507331,0.429905,0.409515
16,sub-0025435,02,30,F,1.345798e+06,0.970233,0.983549,0.557512,0.542390,0.572360,...,0.578885,0.611368,0.579071,0.580645,0.535650,0.538211,0.465912,0.528620,0.429522,0.436629
17,sub-0025435,03,30,F,1.348957e+06,0.976732,0.980530,0.559112,0.542304,0.568774,...,0.571755,0.610324,0.574063,0.574364,0.539471,0.529059,0.464177,0.519967,0.445209,0.442202
18,sub-0025435,04,30,F,1.355278e+06,0.956111,0.979609,0.543191,0.536935,0.574184,...,0.575334,0.613263,0.575106,0.576331,0.558064,0.528151,0.484164,0.518132,0.433163,0.434918
19,sub-0025435,05,30,F,1.354093e+06,0.976870,0.986988,0.548496,0.537534,0.570720,...,0.574705,0.612017,0.587004,0.572613,0.543125,0.520708,0.464794,0.514051,0.447021,0.442245
20,sub-0025440,01,24,M,1.412080e+06,1.073823,1.092055,0.599325,0.615967,0.634663,...,0.714798,0.694772,0.672991,0.635569,0.609558,0.603889,0.530854,0.584627,0.486643,0.425507
21,sub-0025440,02,24,M,1.406342e+06,1.094730,1.119493,0.607474,0.623926,0.642053,...,0.699532,0.691966,0.653760,0.634978,0.599565,0.595928,0.537366,0.590060,0.483036,0.415595
22,sub-0025440,03,24,M,1.383582e+06,1.079361,1.087757,0.609701,0.622223,0.638887,...,0.685241,0.672461,0.634472,0.601081,0.589299,0.585942,0.521544,0.587187,0.480572,0.465685
23,sub-0025440,04,24,M,1.420990e+06,1.081472,1.098209,0.606976,0.615849,0.625854,...,0.710360,0.685524,0.656523,0.611327,0.591396,0.585472,0.522896,0.572364,0.453390,0.405347
24,sub-0025440,05,24,M,1.403503e+06,1.086373,1.104579,0.606689,0.616705,0.635374,...,0.704620,0.676749,0.653130,0.608205,0.605313,0.591541,0.524309,0.586592,0.478131,0.465699
25,sub-0025445,01,23,F,1.464986e+06,1.061621,1.108490,0.625424,0.613667,0.588617,...,0.651824,0.649704,0.652227,0.653939,0.583920,0.543455,0.478824,0.469747,0.442716,0.405148
26,sub-0025445,02,23,F,1.466683e+06,1.072829,1.109240,0.622248,0.600560,0.561441,...,0.632346,0.645178,0.622648,0.645588,0.539732,0.540860,0.453876,0.453780,0.429514,0.400477
27,sub-0025445,04,23,F,1.450042e+06,1.074924,1.119080,0.630885,0.609615,0.580599,...,0.628968,0.649223,0.625862,0.647787,0.540635,0.545644,0.444166,0.464721,0.428492,0.372183
28,sub-0025445,05,23,F,1.456292e+06,1.068568,1.107019,0.620372,0.599198,0.572669,...,0.647695,0.643407,0.644904,0.647073,0.582488,0.541631,0.466932,0.480460,0.422546,0.373466
29,sub-0025445,06,23,F,1.468118e+06,1.065960,1.111987,0.620034,0.602253,0.581087,...,0.647120,0.647711,0.643084,0.655122,0.579896,0.540782,0.479132,0.477028,0.451487,0.375414
30,sub-0025446,01,30,M,1.498093e+06,1.194166,1.114276,0.702372,0.651424,0.629569,...,0.707348,0.715279,0.674191,0.667823,0.591564,0.652170,0.523964,0.614316,0.509915,0.471171
31,sub-0025446,02,30,M,1.501302e+06,1.171079,1.113505,0.698166,0.655139,0.632459,...,0.702372,0.703098,0.685070,0.666644,0.616174,0.664441,0.540541,0.614132,0.484612,0.445996
32,sub-0025446,03,30,M,1.488073e+06,1.176561,1.111450,0.693723,0.663711,0.634369,...,0.720459,0.722517,0.687724,0.682834,0.616549,0.660263,0.537647,0.615675,0.532412,0.499561
33,sub-0025446,04,30,M,1.493331e+06,1.171777,1.101187,0.694475,0.638859,0.623391,...,0.706975,0.719852,0.689568,0.671476,0.612599,0.660899,0.539701,0.618008,0.463701,0.447337
34,sub-0025446,05,30,M,1.496265e+06,1.171521,1.104490,0.696965,0.662826,0.622443,...,0.700174,0.724389,0.675877,0.681413,0.611783,0.659588,0.556892,0.613641,0.496683,0.487961
35,sub-0025447,01,26,M,1.696789e+06,1.134620,1.209468,0.654175,0.706254,0.807179,...,0.679090,0.734638,0.662962,0.673372,0.631625,0.610543,0.556504,0.601572,0.605631,0.539313
36,sub-0025447,02,26,M,1.602568e+06,1.141216,1.202585,0.652475,0.716257,0.811905,...,0.646426,0.721588,0.646053,0.671257,0.640816,0.604036,0.558246,0.581577,0.630239,0.574163
37,sub-0025447,03,26,M,1.691454e+06,1.110016,1.169678,0.668271,0.703894,0.775047,...,0.687671,0.718108,0.709672,0.663509,0.633991,0.598936,0.545943,0.575366,0.573167,0.493669
38,sub-0025447,04,26,M,1.706511e+06,1.123243,1.181818,0.662706,0.703682,0.808457,...,0.690979,0.721063,0.704558,0.670158,0.643822,0.600939,0.562134,0.602657,0.666268,0.579308
39,sub-0025447,05,26,M,1.698021e+06,1.090264,1.187759,0.667085,0.707206,0.779275,...,0.694864,0.728589,0.712006,0.673405,0.654918,0.606841,0.558788,0.591573,0.641804,0.554421
40,sub-0025448,01,23,M,1.698270e+06,1.392041,1.379608,0.827102,0.768113,0.728908,...,0.843316,0.881097,0.813272,0.866261,0.770835,0.761262,0.719965,0.768710,0.615356,0.503899
41,sub-0025448,02,23,M,1.676777e+06,1.395374,1.386020,0.813188,0.779191,0.723782,...,0.840359,0.861796,0.817438,0.826631,0.771378,0.730663,0.699692,0.740392,0.607691,0.499499
42,sub-0025448,03,23,M,1.697903e+06,1.389169,1.382548,0.817447,0.762945,0.723104,...,0.842317,0.868074,0.803827,0.823501,0.763687,0.724990,0.705237,0.750719,0.597729,0.496159
43,sub-0025448,05,23,M,1.688358e+06,1.395671,1.387852,0.818494,0.770364,0.705011,...,0.860438,0.874258,0.815394,0.844467,0.773061,0.741541,0.705498,0.747897,0.629459,0.500172
44,sub-0025448,06,23,M,1.685445e+06,1.410809,1.393984,0.823539,0.773015,0.718370,...,0.838135,0.870292,0.819362,0.838116,0.778285,0.752947,0.712617,0.770682,0.618456,0.506605
45,sub-0025449,02,22,M,1.752653e+06,1.276696,1.337338,0.788822,0.788833,0.734245,...,0.846817,0.813641,0.788421,0.794557,0.728327,0.735478,0.688939,0.753408,0.585146,0.594737
46,sub-0025449,03,22,M,1.751481e+06,1.299503,1.339413,0.789467,0.785314,0.735880,...,0.828438,0.813128,0.776259,0.785480,0.755457,0.723729,0.701325,0.741572,0.555817,0.574652
47,sub-0025449,04,22,M,1.757391e+06,1.292695,1.352967,0.792962,0.782402,0.749090,...,0.815376,0.804405,0.796697,0.765759,0.726388,0.714968,0.695999,0.753711,0.560459,0.564339
48,sub-0025449,05,22,M,1.745821e+06,1.294789,1.344302,0.793214,0.782451,0.754391,...,0.845379,0.811361,0.804095,0.784433,0.738007,0.729068,0.692152,0.758334,0.567161,0.624394
49,sub-0025449,06,22,M,1.755399e+06,1.288999,1.357825,0.800932,0.781895,0.757466,...,0.841087,0.814044,0.798402,0.787663,0.746439,0.737136,0.690586,0.755145,0.581252,0.586204
50,sub-0025450,01,25,F,1.366127e+06,1.082955,1.110987,0.599384,0.623353,0.598844,...,0.642126,0.603238,0.620808,0.647426,0.564700,0.586008,0.531282,0.538030,0.489792,0.416857
51,sub-0025450,02,25,F,1.361626e+06,1.082241,1.093168,0.606352,0.625841,0.595764,...,0.602548,0.603970,0.565340,0.591384,0.508609,0.523846,0.497648,0.498980,0.482677,0.439308
52,sub-0025450,03,25,F,1.359818e+06,1.070082,1.113773,0.596179,0.629308,0.581889,...,0.639721,0.629003,0.647089,0.667685,0.580482,0.600107,0.545635,0.535364,0.489190,0.418357
53,sub-0025450,04,25,F,1.363799e+06,1.077285,1.112895,0.588936,0.628656,0.598171,...,0.655048,0.629700,0.643507,0.659976,0.574476,0.612093,0.534084,0.546880,0.493371,0.459809
54,sub-0025450,05,25,F,1.358742e+06,1.089648,1.098077,0.603630,0.619079,0.590679,...,0.640136,0.605060,0.626700,0.642118,0.578723,0.603377,0.544281,0.534555,0.512012,0.453138
55,sub-0025455,01,25,M,1.553103e+06,1.081198,1.087411,0.689378,0.671418,0.613211,...,0.691707,0.694309,0.663181,0.642122,0.631067,0.593612,0.564783,0.621628,0.425681,0.362052
56,sub-0025455,02,25,M,1.558955e+06,1.085715,1.090107,0.675023,0.668780,0.607555,...,0.668629,0.689106,0.666990,0.645047,0.613568,0.581387,0.538534,0.609823,0.388781,0.400344
57,sub-0025455,03,25,M,1.550227e+06,1.079418,1.092460,0.686868,0.677951,0.609472,...,0.673199,0.684329,0.651510,0.630518,0.621983,0.568393,0.545964,0.601745,0.386872,0.383750
58,sub-0025455,04,25,M,1.540075e+06,1.098021,1.093003,0.684616,0.682546,0.623665,...,0.679383,0.695517,0.653521,0.644637,0.625449,0.585910,0.567247,0.609460,0.406630,0.378038
59,sub-0025455,05,25,M,1.551094e+06,1.068581,1.076606,0.682058,0.666191,0.614100,...,0.673694,0.679468,0.658384,0.628131,0.608825,0.590715,0.544623,0.618673,0.379493,0.398173

In [10]:
# Scale data
scaler = MinMaxScaler()

# Divide by ICV and scale
suit_scaled = suit_df.copy()
suit_scaled.iloc[:,4:] = scaler.fit_transform(suit_scaled.iloc[:,4:].div(suit_scaled.ICV, axis=0))

# Save
if save :
    suit_scaled.to_csv(suit+'suit_all_volumes_cm3_scaled.csv', index=False)

suit_scaled

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,0.0,1.000000,0.774192,0.927170,0.656563,0.771934,...,0.850442,0.499351,0.853695,0.622401,0.925349,0.642938,0.945934,0.975628,0.790194,0.807046
1,sub-0025428,04,28,F,0.0,0.928569,0.695222,0.882268,0.630623,0.753595,...,0.761941,0.376181,0.822532,0.600680,0.817917,0.619079,0.872327,0.904500,0.732715,0.722330
2,sub-0025428,05,28,F,0.0,0.887177,0.629661,0.879734,0.652622,0.792267,...,0.831268,0.528017,0.907446,0.624975,0.977749,0.601535,1.000000,0.886532,0.716356,0.645117
3,sub-0025428,06,28,F,0.0,0.908664,0.684058,0.896090,0.670939,0.770262,...,0.672850,0.435776,0.866322,0.606817,0.861882,0.567215,0.905924,0.877678,0.630104,0.739924
4,sub-0025428,07,28,F,0.0,0.943794,0.681421,0.917894,0.677813,0.803739,...,0.645171,0.335883,0.614751,0.620598,0.435896,0.606085,0.659428,0.802733,0.642059,0.628995
5,sub-0025432,01,21,M,0.0,0.891290,1.000000,1.000000,0.995172,0.943343,...,0.945001,0.984262,0.905922,0.857273,0.969628,0.891238,0.965256,0.909206,1.000000,0.828862
6,sub-0025432,03,21,M,0.0,0.899763,0.931898,0.915823,1.000000,0.795922,...,0.996611,1.000000,0.979237,1.000000,0.930608,1.000000,0.951281,0.979355,0.809668,0.965317
7,sub-0025432,04,21,M,0.0,0.834199,0.807994,0.860808,0.852646,0.936025,...,0.841108,0.736705,0.854546,0.853742,0.931608,0.841746,0.816676,0.842319,0.697013,0.527060
8,sub-0025432,05,21,M,0.0,0.919791,0.870535,0.927593,0.893162,0.937312,...,0.931816,0.856422,0.961381,0.790208,0.901456,0.873150,0.990196,0.880117,0.761243,0.860353
9,sub-0025432,06,21,M,0.0,0.907801,0.989442,0.823805,0.870919,0.896055,...,1.000000,0.877433,1.000000,0.837788,1.000000,0.807757,0.995676,0.960598,0.929707,1.000000
10,sub-0025434,03,24,M,0.0,0.652291,0.539646,0.515334,0.573803,0.505156,...,0.678392,0.455683,0.553143,0.594336,0.701951,0.716369,0.508024,0.704013,0.556192,0.542538
11,sub-0025434,05,24,M,0.0,0.647285,0.553544,0.464186,0.497745,0.471619,...,0.653666,0.363471,0.508887,0.500642,0.653649,0.613070,0.456207,0.672302,0.483938,0.531760
12,sub-0025434,07,24,M,0.0,0.696458,0.644172,0.632786,0.739046,0.531280,...,0.633512,0.538775,0.575196,0.674012,0.692673,0.808962,0.577477,0.724463,0.509679,0.588004
13,sub-0025434,08,24,M,0.0,0.669946,0.588553,0.527319,0.607267,0.507497,...,0.547970,0.446120,0.426203,0.573166,0.570934,0.744059,0.490303,0.730841,0.571189,0.517101
14,sub-0025434,09,24,M,0.0,0.653078,0.562402,0.542906,0.575574,0.479372,...,0.468195,0.407580,0.463549,0.519970,0.619353,0.684660,0.576225,0.712014,0.569643,0.494279
15,sub-0025435,01,30,F,0.0,0.290343,0.116220,0.134224,0.000000,0.271114,...,0.132011,0.222814,0.187095,0.196269,0.236313,0.190744,0.392696,0.442722,0.371990,0.368461
16,sub-0025435,02,30,F,0.0,0.329719,0.175310,0.246758,0.065228,0.343192,...,0.229023,0.239533,0.279374,0.248138,0.284335,0.334758,0.331400,0.564033,0.379690,0.484399
17,sub-0025435,03,30,F,0.0,0.342804,0.157695,0.248611,0.056992,0.313679,...,0.180855,0.225665,0.246039,0.212250,0.302331,0.280658,0.313972,0.514431,0.435153,0.502279
18,sub-0025435,04,30,F,0.0,0.265066,0.139547,0.131087,0.009302,0.330034,...,0.185938,0.226103,0.237460,0.208864,0.414601,0.263147,0.423176,0.493116,0.382006,0.465664
19,sub-0025435,05,30,F,0.0,0.331746,0.166670,0.167758,0.015752,0.312371,...,0.185223,0.222148,0.302127,0.193833,0.313520,0.227019,0.306919,0.474995,0.435592,0.495855
20,sub-0025440,01,24,M,0.0,0.494963,0.365025,0.334091,0.336392,0.538286,...,0.811188,0.524325,0.606398,0.366222,0.603101,0.529134,0.578508,0.707580,0.509509,0.361842
21,sub-0025440,02,24,M,0.0,0.570095,0.466109,0.398742,0.397173,0.595527,...,0.743907,0.524417,0.523577,0.375191,0.552486,0.501695,0.629724,0.745132,0.503605,0.330978
22,sub-0025440,03,24,M,0.0,0.577189,0.422210,0.473614,0.446740,0.637699,...,0.727481,0.479113,0.479136,0.267065,0.548629,0.499960,0.586931,0.777764,0.523324,0.548791
23,sub-0025440,04,24,M,0.0,0.497531,0.362709,0.357479,0.313359,0.465461,...,0.762985,0.451936,0.503467,0.240298,0.456412,0.419526,0.512389,0.631659,0.379222,0.276569
24,sub-0025440,05,24,M,0.0,0.551780,0.425898,0.401445,0.362466,0.564553,...,0.779357,0.450116,0.527043,0.260157,0.599438,0.485797,0.558847,0.734156,0.489333,0.523504
25,sub-0025445,01,23,F,0.0,0.345306,0.290492,0.355460,0.194846,0.153381,...,0.342243,0.158106,0.384786,0.342688,0.289704,0.131858,0.170604,0.076133,0.293249,0.230409
26,sub-0025445,02,23,F,0.0,0.373753,0.288869,0.332611,0.117874,0.000000,...,0.236659,0.130946,0.238751,0.303358,0.000000,0.116452,0.026129,0.000000,0.245591,0.211820
27,sub-0025445,04,23,F,0.0,0.414894,0.357845,0.425608,0.207288,0.142167,...,0.256699,0.190089,0.288804,0.344955,0.045890,0.169221,0.000000,0.075044,0.259129,0.124939
28,sub-0025445,05,23,F,0.0,0.383341,0.306134,0.347551,0.134097,0.084318,...,0.340876,0.145453,0.368046,0.329706,0.302925,0.138596,0.118966,0.138832,0.231852,0.123771
29,sub-0025445,06,23,F,0.0,0.351200,0.293919,0.316096,0.124026,0.105042,...,0.310455,0.140724,0.334109,0.341762,0.255692,0.113552,0.166554,0.105050,0.320416,0.119853
30,sub-0025446,01,30,M,0.0,0.648286,0.233143,0.715658,0.325135,0.302431,...,0.550669,0.414450,0.418840,0.338911,0.254605,0.582905,0.360947,0.680845,0.487837,0.431755
31,sub-0025446,02,30,M,0.0,0.576861,0.223759,0.682983,0.337760,0.310722,...,0.517572,0.345526,0.463215,0.327900,0.401866,0.633656,0.446481,0.674088,0.398225,0.339241
32,sub-0025446,03,30,M,0.0,0.621262,0.247008,0.692848,0.416523,0.351331,...,0.642440,0.475414,0.504452,0.421810,0.438809,0.641553,0.456918,0.705694,0.576573,0.544183
33,sub-0025446,04,30,M,0.0,0.596223,0.204627,0.683074,0.267716,0.279844,...,0.560281,0.449046,0.501681,0.363405,0.399936,0.633592,0.457775,0.706408,0.335639,0.352415
34,sub-0025446,05,30,M,0.0,0.589076,0.208025,0.689536,0.391741,0.268116,...,0.518383,0.464798,0.430676,0.399884,0.387155,0.621372,0.547351,0.681183,0.444883,0.493310
35,sub-0025447,01,26,M,0.0,0.111253,0.094891,0.000000,0.173116,0.750323,...,0.000000,0.078645,0.000000,0.029003,0.040268,0.053800,0.179990,0.305302,0.572197,0.449414
36,sub-0025447,02,26,M,0.0,0.292848,0.262644,0.185615,0.424067,1.000000,...,0.024093,0.209281,0.087703,0.168422,0.301869,0.173582,0.349240,0.361894,0.757416,0.663882
37,sub-0025447,03,26,M,0.0,0.059252,0.000000,0.082035,0.172441,0.609033,...,0.048488,0.015202,0.203694,0.000000,0.064638,0.013667,0.136704,0.208084,0.480110,0.311595
38,sub-0025447,04,26,M,0.0,0.067448,0.004518,0.024078,0.141426,0.734486,...,0.035869,0.000000,0.156396,0.002754,0.087873,0.000000,0.191872,0.295941,0.742935,0.564121
39,sub-0025447,05,26,M,0.0,0.000000,0.035563,0.062912,0.175230,0.614828,...,0.068878,0.049390,0.201943,0.027303,0.167631,0.036693,0.189185,0.263739,0.679452,0.495383
40,sub-0025448,01,23,M,0.0,0.742604,0.538934,0.871851,0.467759,0.374784,...,0.737488,0.726557,0.622546,0.746168,0.813545,0.673461,0.977353,0.968793,0.599795,0.337333
41,sub-0025448,02,23,M,0.0,0.794848,0.602433,0.854200,0.569113,0.394525,...,0.772707,0.689880,0.683437,0.637891,0.871718,0.585855,0.922049,0.893818,0.600169,0.343589
42,sub-0025448,03,23,M,0.0,0.736273,0.547440,0.823911,0.443693,0.347929,...,0.733806,0.669527,0.584001,0.587366,0.774603,0.524453,0.906043,0.897796,0.547281,0.313496
43,sub-0025448,05,23,M,0.0,0.771714,0.581983,0.852617,0.500350,0.280832,...,0.837424,0.718973,0.651274,0.683379,0.851270,0.610058,0.926838,0.903395,0.653212,0.334864
44,sub-0025448,06,23,M,0.0,0.815244,0.604544,0.885529,0.519644,0.350664,...,0.742879,0.707970,0.673791,0.664991,0.888122,0.662794,0.967932,1.000000,0.623223,0.357827
45,sub-0025449,02,22,M,0.0,0.361082,0.318950,0.554405,0.449686,0.291826,...,0.634841,0.314648,0.417506,0.386810,0.450452,0.472919,0.720966,0.814762,0.454639,0.563412
46,sub-0025449,03,22,M,0.0,0.417568,0.326511,0.560156,0.435731,0.301627,...,0.557002,0.314784,0.370603,0.355908,0.599791,0.427884,0.781911,0.771006,0.370432,0.503791
47,sub-0025449,04,22,M,0.0,0.390937,0.349440,0.564218,0.409873,0.350921,...,0.487936,0.265550,0.442199,0.275284,0.429392,0.383215,0.745544,0.808088,0.378454,0.466811
48,sub-0025449,05,22,M,0.0,0.416335,0.350058,0.591147,0.434208,0.398254,...,0.643009,0.318503,0.493333,0.361321,0.518368,0.458698,0.749042,0.845219,0.408793,0.660560
49,sub-0025449,06,22,M,0.0,0.385625,0.365680,0.607621,0.411641,0.393359,...,0.604072,0.310902,0.452689,0.357446,0.542018,0.474940,0.723654,0.816906,0.440671,0.534812
50,sub-0025450,01,25,F,0.0,0.629867,0.542851,0.457109,0.500448,0.448639,...,0.534350,0.143614,0.449883,0.517083,0.429633,0.538218,0.686180,0.571088,0.580343,0.382021
51,sub-0025450,02,25,F,0.0,0.638630,0.496473,0.513527,0.527702,0.442071,...,0.323765,0.158683,0.172848,0.266328,0.052422,0.228262,0.491621,0.385939,0.559751,0.474827
52,sub-0025450,03,25,F,0.0,0.605661,0.568814,0.454344,0.553526,0.364373,...,0.537504,0.302051,0.601239,0.625366,0.557712,0.624812,0.788874,0.570183,0.586564,0.395381
53,sub-0025450,04,25,F,0.0,0.618142,0.555279,0.397729,0.538582,0.450696,...,0.613017,0.295719,0.572882,0.580489,0.504208,0.677369,0.708767,0.619518,0.596836,0.551838
54,sub-0025450,05,25,F,0.0,0.668479,0.520186,0.504436,0.495014,0.419351,...,0.542695,0.171845,0.497939,0.508653,0.548658,0.644124,0.783230,0.568266,0.673622,0.532450
55,sub-0025455,01,25,M,0.0,0.226101,0.038498,0.501126,0.304483,0.097175,...,0.345579,0.184954,0.256234,0.134100,0.363033,0.210669,0.476395,0.614456,0.149958,0.000000
56,sub-0025455,02,25,M,0.0,0.227288,0.034488,0.407711,0.277396,0.055904,...,0.219477,0.147104,0.262166,0.136151,0.242280,0.145671,0.325147,0.553083,0.024076,0.125640
57,sub-0025455,03,25,M,0.0,0.226698,0.058816,0.494292,0.345465,0.083609,...,0.260522,0.142631,0.208666,0.091548,0.314677,0.101648,0.381130,0.532739,0.024955,0.076533
58,sub-0025455,04,25,M,0.0,0.296399,0.081107,0.506819,0.393398,0.178963,...,0.313168,0.219409,0.237449,0.166595,0.361037,0.198281,0.515249,0.583924,0.098729,0.065516
59,sub-0025455,05,25,M,0.0,0.195858,0.011475,0.465525,0.281519,0.105929,...,0.261107,0.117121,0.238301,0.080363,0.232208,0.201049,0.372312,0.605078,0.000000,0.125120

# CERES

In [11]:
# Columns to keep and convert
col = {
    'ICV cm3':'ICV',
    'I-II right cm3':'Right.I.II',
    'I-II left cm3':'Left.I.II',
    'III right cm3':'Right.III',
    'III left cm3':'Left.III',
    'IV right cm3':'Right.IV',
    'IV left cm3':'Left.IV',
    'V right cm3':'Right.V',
    'V left cm3':'Left.V',
    'VI right cm3':'Right.VI',
    'VI left cm3':'Left.VI',
    'Crus I right cm3':'Right.Crus.I',
    'Crus I left cm3':'Left.Crus.I',
    'Crus II right cm3':'Right.Crus.II',
    'Crus II left cm3':'Left.Crus.II',
    'VIIB right cm3':'Right.VIIB',
    'VIIB left cm3':'Left.VIIB',
    'VIIIA right cm3':'Right.VIIIA',
    'VIIIA left cm3':'Left.VIIIA',
    'VIIIB right cm3':'Right.VIIIB',
    'VIIIB left cm3':'Left.VIIIB',
    'IX right cm3':'Right.IX',
    'IX left cm3':'Left.IX',
    'X right cm3':'Right.X',
    'X left cm3':'Left.X',
}

In [12]:
# List to store DataFrames
all_data = []

# Loop through subjects and sessions
for sub in subjects_list:
    sessions = subjects[subjects['ID']==sub]['good_ses'].iloc[0].split(';')
    for ses in sessions:
        ses_str = f"{int(ses):02d}"
        
        # Get the matching file (for given subject and given session)
        dataFile = glob.glob(os.path.join(ceres, 'output', f"{sub}_ses-{ses_str}_T1w_job*_archive", "report_job*.csv"))[0]

        # Read CSV
        data = pd.read_csv(dataFile, sep=';')

        # Keep only the columns in col and rename them
        data = data[list(col.keys())].rename(columns=col)

        # Group I.II, III, IV and V into I.V
        data.insert(4, "Left.I.V", data["Left.I.II"] + data["Left.III"] + data["Left.IV"] + data["Left.V"])
        data.insert(4, "Right.I.V", data["Right.I.II"] + data["Right.III"] + data["Right.IV"] + data["Right.V"])
        data = data.drop(["Left.I.II", "Left.III", "Left.IV", "Left.V", "Right.I.II", "Right.III", "Right.IV", "Right.V"], axis = 1)

        # Add Subject ID and Session columns at the beginning
        data.insert(0, 'ses', ses_str)
        data.insert(0, 'ID', sub)

        # Append to the list
        all_data.append(data)

# Concatenate all DataFrames into one
ceres_df = pd.concat(all_data, ignore_index=True)

# Merge with age and sex
ceres_df= ceres_df.merge(subjects, on="ID", how="left")

# Sort columns
ceres_df = ceres_df[finalColumns]

# Save it
if save :
    ceres_df.to_csv(ceres+'ceres_all_volumes_cm3.csv', index=False)

ceres_df

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,1366.2293,8.619207,8.284889,9.3166,9.6142,13.7456,...,4.4173,3.9308,6.0729,5.7547,4.6002,4.8214,4.2762,4.5613,0.67754,0.76646
1,sub-0025428,04,28,F,1369.8166,8.507694,8.410795,9.1906,9.7826,13.6649,...,4.7743,4.0400,5.7368,5.9833,4.6621,5.0157,4.1485,4.4919,0.68959,0.75048
2,sub-0025428,05,28,F,1360.8444,8.616637,8.130018,9.2284,9.9946,14.3354,...,4.4075,4.1506,6.1967,6.0598,4.4616,4.8385,4.2582,4.4872,0.66957,0.72811
3,sub-0025428,06,28,F,1365.8614,8.680817,8.318745,9.0717,9.8676,14.1545,...,4.4138,4.0671,5.8964,5.7238,4.5436,4.7273,4.2589,4.4558,0.67269,0.73244
4,sub-0025428,07,28,F,1358.9255,8.588919,8.133727,9.2548,10.4579,14.1116,...,4.5217,3.7899,5.7679,5.7123,4.2941,4.4990,4.0833,4.3073,0.71641,0.74861
5,sub-0025432,01,21,M,1590.6229,7.559628,8.096501,8.7325,9.3029,12.0194,...,5.0898,5.9984,7.5361,6.5378,4.2492,3.7173,3.4648,3.5932,0.64682,0.74581
6,sub-0025432,03,21,M,1601.7250,7.531538,8.151023,8.5726,9.5626,11.7738,...,5.0101,5.8115,7.4360,6.4259,4.5726,3.9171,3.4678,3.7771,0.64963,0.70412
7,sub-0025432,04,21,M,1610.0467,7.780752,7.935952,8.6375,9.3695,12.2568,...,4.8302,5.2763,7.0193,6.3801,4.8917,3.7837,3.4059,3.5822,0.59365,0.72352
8,sub-0025432,05,21,M,1598.3493,7.436855,8.148016,8.7440,9.5253,12.3025,...,5.0778,6.3166,7.7331,6.9025,4.0060,3.8190,3.3674,3.4801,0.64860,0.73625
9,sub-0025432,06,21,M,1610.8941,7.575204,8.315088,8.6575,9.4548,12.1149,...,4.9802,5.5079,7.6809,6.1927,3.9056,3.7787,3.4422,3.6274,0.66206,0.72463
10,sub-0025434,03,24,M,1402.7339,7.240692,6.653297,7.6716,7.9788,10.8914,...,4.3348,4.1617,6.3355,5.6604,4.2029,4.3873,2.8159,3.0160,0.54251,0.52078
11,sub-0025434,05,24,M,1410.6375,7.276687,6.727409,7.1922,7.5574,10.6189,...,3.9187,3.9828,6.3191,5.5275,4.1745,4.1013,2.7890,2.9883,0.51012,0.50710
12,sub-0025434,07,24,M,1398.1310,7.258175,6.911092,7.7054,8.0226,10.4107,...,4.9164,4.2558,5.4047,5.8220,4.0527,4.3827,2.8091,2.9950,0.56286,0.56435
13,sub-0025434,08,24,M,1397.5474,7.320333,6.623789,7.1571,7.8619,10.4723,...,3.8224,3.9388,5.5565,5.7914,4.2602,4.4556,2.7066,3.0415,0.51612,0.53327
14,sub-0025434,09,24,M,1403.4750,7.364429,6.616869,7.3209,7.7705,10.1768,...,3.7941,3.9899,6.0202,5.7620,4.1896,4.2977,2.7741,3.0412,0.52614,0.52914
15,sub-0025435,01,30,F,1316.9614,6.433634,6.190782,5.9486,6.9334,10.8172,...,3.7547,4.2135,5.2691,5.4822,4.4383,3.8831,3.0593,3.0531,0.56772,0.57952
16,sub-0025435,02,30,F,1311.3529,6.375959,6.059471,6.2178,7.0701,10.9922,...,3.7301,4.2440,5.2243,5.4803,4.5391,4.0073,3.0807,3.0834,0.54693,0.59233
17,sub-0025435,03,30,F,1309.7646,6.559785,6.023625,6.1755,6.9164,10.8869,...,3.6738,4.3631,5.1689,5.4386,4.3886,3.8739,3.0936,3.1412,0.56642,0.58229
18,sub-0025435,04,30,F,1320.1713,6.440563,6.236906,5.8529,6.9167,10.6706,...,3.7623,4.2468,5.2227,5.4116,4.4629,3.8055,3.0540,3.0617,0.57999,0.61066
19,sub-0025435,05,30,F,1319.6493,6.562047,6.206217,6.0598,6.8173,10.8501,...,3.7030,4.2456,5.2109,5.4864,4.5476,3.9380,3.0215,3.0320,0.57682,0.59705
20,sub-0025440,01,24,M,1506.4000,6.969563,6.560594,7.0978,7.2213,10.7108,...,4.8124,4.7436,7.3198,5.6114,4.4934,4.2917,3.6544,3.7631,0.59265,0.57623
21,sub-0025440,02,24,M,1511.3390,7.218340,6.552757,7.2239,7.4124,11.1534,...,4.7986,4.8333,7.0559,5.5219,4.2078,4.2938,3.5729,3.6826,0.58997,0.52214
22,sub-0025440,03,24,M,1500.5660,6.995723,6.510558,7.4664,7.3753,10.9888,...,5.0965,4.8302,6.7697,5.5499,4.3340,4.2992,3.5913,3.8458,0.55879,0.58416
23,sub-0025440,04,24,M,1487.9671,7.148038,6.631076,7.1811,7.1363,10.8470,...,4.8382,4.8822,7.1732,5.5563,4.3613,4.2780,3.5654,3.6832,0.54919,0.58533
24,sub-0025440,05,24,M,1509.7525,7.048324,6.568779,7.4015,7.3481,11.0390,...,4.7598,4.7889,7.2618,5.4709,4.3502,4.2152,3.6093,3.7969,0.57918,0.59410
25,sub-0025445,01,23,F,1446.6846,7.946362,7.986047,6.6471,6.0134,10.7000,...,4.3492,4.3370,6.5020,4.8156,4.0972,3.3415,2.5849,2.8811,0.47561,0.56493
26,sub-0025445,02,23,F,1454.1303,7.740972,8.168457,6.4695,6.2353,10.4420,...,3.6267,4.2899,6.6142,4.7797,4.2059,3.5312,2.6055,2.5215,0.51371,0.52911
27,sub-0025445,04,23,F,1447.1556,7.582021,7.650883,7.1515,7.0031,10.8679,...,4.5194,4.3703,6.3019,4.9644,4.1890,3.3861,2.6856,2.5266,0.51847,0.54523
28,sub-0025445,05,23,F,1448.2686,7.889703,7.593498,6.9109,6.5742,10.9107,...,3.9708,4.4327,6.5147,4.9473,4.3296,3.3539,2.4507,2.7340,0.49778,0.54970
29,sub-0025445,06,23,F,1452.7591,7.797749,7.717064,6.9494,6.5116,10.8468,...,4.1304,4.4053,6.4941,4.8203,4.3596,3.6354,2.6477,2.5091,0.52163,0.53229
30,sub-0025446,01,30,M,1490.7264,7.166654,5.956655,6.5535,8.1488,11.9442,...,4.1295,3.8403,6.5613,6.8016,3.9527,5.5923,3.4240,3.8651,0.67287,0.66434
31,sub-0025446,02,30,M,1488.4625,7.032657,6.043198,6.1988,8.0812,12.2124,...,4.4836,4.0184,6.5099,6.3987,3.8963,5.6706,3.4623,3.8870,0.64329,0.64018
32,sub-0025446,03,30,M,1482.9770,7.044193,6.020576,5.9242,8.0300,12.0049,...,4.0181,3.6913,6.7235,6.9771,3.9919,5.6436,3.4569,3.9186,0.69910,0.66981
33,sub-0025446,04,30,M,1487.7996,7.365577,6.069783,6.3442,7.9362,12.0938,...,4.4931,4.1204,6.4370,6.8422,3.9929,5.2455,3.6001,3.9302,0.64950,0.63326
34,sub-0025446,05,30,M,1489.3440,7.203106,5.956833,6.0280,8.1131,11.6098,...,4.1965,3.3940,6.5506,6.9913,4.1408,6.4485,3.4929,4.0217,0.63627,0.68730
35,sub-0025447,01,26,M,1667.9889,7.168279,7.490904,7.9312,8.9331,13.8840,...,4.1923,5.4941,6.7646,5.7505,3.8950,3.6334,3.1966,3.2864,0.73680,0.67663
36,sub-0025447,02,26,M,1639.7755,6.985169,7.492194,7.9950,9.1783,14.0919,...,4.0244,5.4420,5.8225,5.4873,3.8517,3.4217,3.1677,3.3370,0.72161,0.74555
37,sub-0025447,03,26,M,1643.7999,7.135997,7.229928,8.1026,9.1711,13.5855,...,4.3109,5.5165,6.6297,5.2853,3.7193,3.4848,3.0743,3.3356,0.58209,0.73903
38,sub-0025447,04,26,M,1666.1450,7.046267,7.398818,7.9109,9.2188,13.8821,...,4.3564,5.5409,6.4013,5.4194,3.9451,3.5847,3.1442,3.2123,0.70436,0.76557
39,sub-0025447,05,26,M,1666.7488,6.903546,7.360130,8.3637,9.1116,14.1906,...,4.5093,5.5642,6.4026,5.3911,4.1127,3.5387,3.1769,3.3222,0.71053,0.75662
40,sub-0025448,01,23,M,1588.2280,10.717076,10.029038,10.2816,9.7622,13.1673,...,4.9929,6.2579,8.5582,8.1236,6.2071,5.1836,4.4575,4.1948,0.59986,0.62020
41,sub-0025448,02,23,M,1583.5762,10.721526,9.920567,10.2000,10.0709,13.1107,...,5.1395,6.3328,8.6975,7.8931,6.1247,4.9925,4.4889,4.2324,0.60475,0.63787
42,sub-0025448,03,23,M,1598.4455,10.733647,10.006530,10.1067,9.6672,13.0005,...,5.9369,6.4951,7.6184,7.9280,6.4128,5.2701,4.5897,4.5362,0.61083,0.58962
43,sub-0025448,05,23,M,1594.5335,10.729488,9.645116,10.2145,10.1271,12.9631,...,6.0513,6.7633,8.2127,8.0260,6.2652,5.2104,4.4628,4.4644,0.62202,0.63560
44,sub-0025448,06,23,M,1604.6265,10.990086,10.009587,10.1823,9.7622,12.9349,...,5.1260,6.3760,8.4645,8.2477,6.3607,5.2969,4.5869,4.4763,0.61141,0.59271
45,sub-0025449,02,22,M,1691.0368,8.152690,8.789702,10.3395,9.8182,14.0796,...,5.3845,5.7078,8.4628,7.2196,5.1697,5.1229,4.1784,4.7403,0.69095,0.77224
46,sub-0025449,03,22,M,1704.3945,8.493498,8.662016,10.4442,10.1757,14.3418,...,5.5410,5.5014,5.9023,7.0096,5.1077,5.2545,4.1544,4.6247,0.64961,0.78025
47,sub-0025449,04,22,M,1681.8330,8.176885,8.997830,10.3327,9.9023,14.2246,...,4.5726,5.2116,9.2020,7.3195,5.3980,5.0465,4.1040,4.7253,0.64702,0.74908
48,sub-0025449,05,22,M,1687.6035,8.075943,8.884868,10.3561,9.7719,14.6270,...,5.9427,5.3371,6.1756,7.3878,4.9187,5.0826,4.1195,4.6508,0.66836,0.78663
49,sub-0025449,06,22,M,1684.8550,8.160803,9.080560,10.3102,9.7003,14.4164,...,5.3491,5.7557,8.4689,6.8584,5.1840,5.0677,4.1772,4.8049,0.66231,0.81768
50,sub-0025450,01,25,F,1355.0242,6.811089,6.988332,7.4933,7.2157,10.0879,...,4.3464,4.5788,4.7158,5.1505,3.9748,3.9561,2.8945,3.0867,0.54159,0.50429
51,sub-0025450,02,25,F,1345.9862,6.759777,6.923333,7.6157,7.4392,10.2447,...,4.3586,4.6201,4.7894,5.3417,4.1865,4.1479,2.9212,3.1856,0.55153,0.58796
52,sub-0025450,03,25,F,1359.1538,6.649073,6.937199,7.5887,7.3520,10.0336,...,3.3510,4.3779,4.9578,5.1044,4.1934,3.9731,2.8769,3.1150,0.52989,0.53847
53,sub-0025450,04,25,F,1357.5329,6.603228,6.973585,7.5244,7.4341,10.2741,...,4.5848,4.5333,5.0153,5.3176,4.1508,4.0046,2.8909,3.1423,0.53935,0.55153
54,sub-0025450,05,25,F,1352.1824,6.833924,6.830398,7.5636,7.2416,10.1446,...,3.8932,4.2545,4.7064,4.9241,4.1102,4.0338,2.9051,3.1200,0.55046,0.54189
55,sub-0025455,01,25,M,1491.3640,7.342164,5.749611,8.6705,9.5901,10.1354,...,3.9915,4.7617,6.5519,6.2146,4.8051,3.7707,3.6229,3.8446,0.60556,0.57905
56,sub-0025455,02,25,M,1489.9835,6.893931,5.864142,8.7710,9.5248,10.0696,...,3.9038,4.9784,6.6571,5.6201,4.7600,3.3589,3.6246,3.7750,0.58410,0.61930
57,sub-0025455,03,25,M,1483.8077,7.388622,5.739593,8.1809,9.3234,9.7471,...,3.9445,4.4455,6.2598,5.6095,4.6489,3.6437,3.3341,3.7562,0.54970,0.58321
58,sub-0025455,04,25,M,1476.3522,7.563934,5.739500,8.4119,9.5275,9.8876,...,3.4987,4.8497,6.4604,5.8705,4.6721,3.3580,3.5622,3.7816,0.58994,0.60521
59,sub-0025455,05,25,M,1484.2859,6.991849,5.710505,8.2057,9.0310,9.9173,...,3.7942,4.0302,6.3704,5.5788,4.5833,3.9130,3.2587,3.7243,0.55716,0.61577

In [13]:
# Scale data
scaler = MinMaxScaler()

# Divide by ICV and scale
ceres_scaled = ceres_df.copy()
ceres_scaled.iloc[:,4:] = scaler.fit_transform(ceres_scaled.iloc[:,4:].div(ceres_scaled.ICV, axis=0))

# Save
if save :
    ceres_scaled.to_csv(ceres+'ceres_all_volumes_cm3_scaled.csv', index=False)

ceres_scaled

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,0.0,0.800433,0.898450,1.000000,0.813882,0.880657,...,0.605794,0.304815,0.483914,0.517916,0.631378,0.643000,1.000000,1.000000,0.842418,1.000000
1,sub-0025428,04,28,F,0.0,0.764258,0.929267,0.961110,0.843411,0.859155,...,0.782717,0.341593,0.357270,0.598893,0.652170,0.702117,0.929460,0.963135,0.880206,0.939055
2,sub-0025428,05,28,F,0.0,0.808957,0.862050,0.986606,0.900735,1.000000,...,0.609718,0.392909,0.537410,0.643064,0.580772,0.654828,0.999414,0.974408,0.822793,0.879543
3,sub-0025428,06,28,F,0.0,0.817723,0.909159,0.937168,0.866839,0.956840,...,0.604607,0.356054,0.420826,0.506751,0.608208,0.612710,0.991777,0.952626,0.825197,0.885134
4,sub-0025428,07,28,F,0.0,0.804725,0.866576,0.996875,1.000000,0.962218,...,0.671892,0.259866,0.385087,0.513467,0.512955,0.545688,0.912971,0.895147,1.000000,0.953044
5,sub-0025432,01,21,M,0.0,0.225593,0.503723,0.529381,0.478072,0.249024,...,0.582410,0.760303,0.628209,0.464976,0.233687,0.111597,0.338098,0.330046,0.392517,0.572551
6,sub-0025432,03,21,M,0.0,0.206946,0.503220,0.480562,0.512431,0.197145,...,0.531934,0.687533,0.581230,0.413876,0.338525,0.159987,0.328900,0.391577,0.387154,0.436704
7,sub-0025432,04,21,M,0.0,0.255147,0.438419,0.485040,0.469823,0.263219,...,0.442190,0.508613,0.441870,0.388322,0.443390,0.117414,0.294377,0.308895,0.201368,0.482069
8,sub-0025432,05,21,M,0.0,0.188732,0.506814,0.522532,0.509400,0.284480,...,0.566289,0.852447,0.677658,0.573206,0.139322,0.134928,0.288391,0.279359,0.388223,0.534283
9,sub-0025432,06,21,M,0.0,0.207072,0.532759,0.488437,0.483920,0.239994,...,0.506418,0.580987,0.643124,0.326795,0.092535,0.115479,0.309276,0.325580,0.414406,0.484169
10,sub-0025434,03,24,M,0.0,0.376761,0.363063,0.521962,0.432705,0.301479,...,0.505489,0.350535,0.519161,0.426034,0.419372,0.464091,0.219283,0.262467,0.292261,0.119612
11,sub-0025434,05,24,M,0.0,0.375503,0.373586,0.390788,0.339290,0.241791,...,0.286371,0.277449,0.500963,0.365337,0.398266,0.365892,0.198197,0.242806,0.165626,0.064964
12,sub-0025434,07,24,M,0.0,0.387657,0.444123,0.536896,0.446848,0.221218,...,0.804505,0.389803,0.198426,0.492990,0.363598,0.467215,0.220497,0.257539,0.372029,0.269876
13,sub-0025434,08,24,M,0.0,0.404888,0.361639,0.398804,0.415034,0.233118,...,0.256279,0.274882,0.252746,0.482517,0.449167,0.491054,0.170069,0.278741,0.204332,0.167472
14,sub-0025434,09,24,M,0.0,0.408322,0.351528,0.432468,0.389919,0.172038,...,0.234026,0.287368,0.407281,0.462540,0.413050,0.434894,0.197831,0.272905,0.232451,0.146340
15,sub-0025435,01,30,F,0.0,0.274572,0.345924,0.184857,0.313085,0.414802,...,0.337640,0.469025,0.265094,0.492280,0.633110,0.384224,0.438763,0.366846,0.515671,0.438755
16,sub-0025435,02,30,F,0.0,0.266043,0.313488,0.264379,0.348902,0.457316,...,0.333033,0.487847,0.256692,0.500778,0.685292,0.432070,0.457024,0.387337,0.445066,0.492813
17,sub-0025435,03,30,F,0.0,0.320067,0.304667,0.254980,0.317591,0.439604,...,0.305293,0.536177,0.238229,0.486869,0.622004,0.388315,0.465855,0.416491,0.522606,0.459787
18,sub-0025435,04,30,F,0.0,0.272123,0.355452,0.155303,0.305893,0.381760,...,0.336816,0.477913,0.242981,0.459236,0.639078,0.354823,0.432042,0.367390,0.557228,0.543236
19,sub-0025435,05,30,F,0.0,0.306842,0.346784,0.211434,0.285196,0.416870,...,0.306077,0.478098,0.239346,0.489529,0.676534,0.400094,0.415550,0.353994,0.545998,0.496232
20,sub-0025440,01,24,M,0.0,0.179054,0.205828,0.253845,0.180012,0.136492,...,0.578732,0.443323,0.687985,0.264850,0.411742,0.339842,0.510344,0.478410,0.325872,0.171859
21,sub-0025440,02,24,M,0.0,0.234275,0.197958,0.277934,0.211314,0.204487,...,0.564999,0.468319,0.594115,0.227757,0.298141,0.336311,0.467324,0.440291,0.310456,0.000000
22,sub-0025440,03,24,M,0.0,0.192138,0.199176,0.347302,0.214277,0.190185,...,0.720290,0.478965,0.516645,0.251081,0.357646,0.347008,0.487657,0.518637,0.219864,0.203280
23,sub-0025440,04,24,M,0.0,0.244534,0.246893,0.294332,0.180651,0.181789,...,0.618666,0.510657,0.669097,0.269586,0.382114,0.351472,0.489645,0.464292,0.203240,0.222223
24,sub-0025440,05,24,M,0.0,0.194529,0.204106,0.321362,0.200736,0.187333,...,0.549308,0.455048,0.663737,0.212200,0.353733,0.314432,0.485821,0.488861,0.276507,0.222838
25,sub-0025445,01,23,F,0.0,0.499020,0.678042,0.212402,0.000000,0.208625,...,0.446600,0.366349,0.508260,0.058930,0.325568,0.099451,0.065808,0.164068,0.000000,0.208879
26,sub-0025445,02,23,F,0.0,0.436454,0.717428,0.160830,0.037105,0.154329,...,0.087174,0.342025,0.534942,0.037247,0.360011,0.152338,0.069298,0.004281,0.123559,0.085306
27,sub-0025445,04,23,F,0.0,0.405358,0.583445,0.335278,0.192861,0.237278,...,0.528435,0.377576,0.439403,0.111791,0.361304,0.112856,0.113801,0.011654,0.148716,0.145127
28,sub-0025445,05,23,F,0.0,0.482349,0.565739,0.275114,0.108130,0.243275,...,0.260966,0.398346,0.510159,0.104287,0.415531,0.102142,0.000000,0.099687,0.075333,0.158104
29,sub-0025445,06,23,F,0.0,0.452747,0.593644,0.279275,0.091989,0.226310,...,0.332104,0.383916,0.496320,0.053379,0.422053,0.185336,0.090678,0.000000,0.152714,0.097056
30,sub-0025446,01,30,M,0.0,0.245862,0.060187,0.142110,0.370059,0.364005,...,0.280872,0.151460,0.462430,0.700028,0.222322,0.742154,0.420588,0.537169,0.617910,0.464763
31,sub-0025446,02,30,M,0.0,0.215308,0.086215,0.060106,0.359575,0.412520,...,0.450749,0.214421,0.448713,0.562995,0.202967,0.768150,0.440914,0.548746,0.521220,0.392596
32,sub-0025446,03,30,M,0.0,0.224638,0.086119,0.000000,0.355494,0.384886,...,0.238321,0.107128,0.527661,0.773904,0.245354,0.766316,0.444366,0.567963,0.718934,0.492683
33,sub-0025446,04,30,M,0.0,0.298746,0.094191,0.095364,0.332720,0.393338,...,0.456171,0.249964,0.425528,0.718870,0.240750,0.641526,0.506054,0.567487,0.543225,0.371904
34,sub-0025446,05,30,M,0.0,0.256552,0.061738,0.018629,0.364719,0.309256,...,0.314241,0.000000,0.460903,0.768408,0.295929,1.000000,0.454247,0.603911,0.496177,0.538212
35,sub-0025447,01,26,M,0.0,0.057492,0.260881,0.269135,0.338774,0.442553,...,0.100729,0.517141,0.291995,0.120682,0.041460,0.040847,0.155992,0.150886,0.569324,0.279203
36,sub-0025447,02,26,M,0.0,0.043556,0.292517,0.311876,0.407064,0.510646,...,0.059227,0.529827,0.043266,0.068105,0.049332,0.000000,0.166668,0.191071,0.560942,0.506603
37,sub-0025447,03,26,M,0.0,0.073598,0.223318,0.330826,0.401954,0.427647,...,0.177304,0.548779,0.280963,0.000000,0.000000,0.014836,0.123859,0.187451,0.127772,0.483034
38,sub-0025447,04,26,M,0.0,0.032197,0.240495,0.266684,0.388901,0.444589,...,0.171787,0.533309,0.186758,0.019413,0.060127,0.028891,0.135593,0.124641,0.473667,0.528967
39,sub-0025447,05,26,M,0.0,0.000000,0.230435,0.362261,0.370161,0.490506,...,0.235489,0.539818,0.186457,0.009979,0.117120,0.016240,0.148763,0.165124,0.491551,0.503280
40,sub-0025448,01,23,M,0.0,0.962624,1.000000,0.877646,0.562278,0.434171,...,0.542986,0.846448,0.948853,0.986976,0.940715,0.524761,0.775109,0.567216,0.246600,0.208871
41,sub-0025448,02,23,M,0.0,0.970984,0.979756,0.866135,0.622462,0.431299,...,0.614422,0.876443,1.000000,0.919155,0.917532,0.475235,0.794634,0.586764,0.267753,0.265967
42,sub-0025448,03,23,M,0.0,0.950520,0.977933,0.824255,0.534383,0.394490,...,0.943266,0.909223,0.642155,0.906409,1.000000,0.539585,0.820155,0.689277,0.269019,0.108523
43,sub-0025448,05,23,M,0.0,0.955642,0.892293,0.853683,0.620073,0.393607,...,1.000000,1.000000,0.831579,0.944664,0.952710,0.526500,0.769702,0.665655,0.309110,0.246518
44,sub-0025448,06,23,M,0.0,1.000000,0.968932,0.832312,0.544529,0.376278,...,0.578645,0.863431,0.892942,1.000000,0.972604,0.541369,0.811248,0.659329,0.263422,0.110865
45,sub-0025449,02,22,M,0.0,0.250896,0.547364,0.750422,0.466044,0.443113,...,0.571368,0.558654,0.759619,0.547651,0.454186,0.420297,0.541639,0.667750,0.402343,0.515886
46,sub-0025449,03,22,M,0.0,0.310804,0.500490,0.755205,0.512455,0.465453,...,0.618285,0.483476,0.000000,0.466249,0.419694,0.444134,0.518376,0.612029,0.263971,0.521085
47,sub-0025449,04,22,M,0.0,0.265957,0.609049,0.760837,0.489152,0.476347,...,0.244872,0.417744,0.989699,0.590652,0.541350,0.407436,0.520275,0.671735,0.281977,0.463587
48,sub-0025449,05,22,M,0.0,0.237720,0.574505,0.758308,0.461630,0.529187,...,0.807996,0.450235,0.096781,0.603948,0.372716,0.412398,0.520860,0.638379,0.339073,0.559760
49,sub-0025449,06,22,M,0.0,0.259210,0.625061,0.752207,0.452291,0.501230,...,0.564823,0.579449,0.770451,0.444403,0.465450,0.410646,0.547449,0.697925,0.324233,0.648797
50,sub-0025450,01,25,F,0.0,0.326781,0.530961,0.543552,0.330166,0.220879,...,0.587840,0.560592,0.008497,0.304338,0.383448,0.371317,0.308788,0.341823,0.357465,0.123799
51,sub-0025450,02,25,F,0.0,0.325167,0.525424,0.588896,0.387189,0.262865,...,0.609313,0.587786,0.046958,0.391405,0.484621,0.443585,0.332561,0.396911,0.408207,0.423822
52,sub-0025450,03,25,F,0.0,0.277105,0.509362,0.562454,0.353930,0.205099,...,0.067132,0.480050,0.091026,0.280714,0.470297,0.372939,0.295267,0.350448,0.307962,0.235236
53,sub-0025450,04,25,F,0.0,0.266788,0.522695,0.548045,0.372844,0.252000,...,0.706901,0.540333,0.114044,0.364643,0.454464,0.384839,0.304198,0.364626,0.345427,0.282069
54,sub-0025450,05,25,F,0.0,0.336922,0.488015,0.566074,0.338740,0.235400,...,0.357402,0.442014,0.008676,0.221494,0.444216,0.399671,0.317362,0.360076,0.394756,0.256449
55,sub-0025455,01,25,M,0.0,0.288576,0.003227,0.644031,0.642476,0.057269,...,0.215115,0.465682,0.458397,0.494511,0.548414,0.196904,0.512665,0.527951,0.389487,0.198527
56,sub-0025455,02,25,M,0.0,0.179133,0.035829,0.669819,0.631776,0.047719,...,0.175555,0.541290,0.495195,0.289209,0.532817,0.074733,0.515024,0.500446,0.318798,0.325537
57,sub-0025455,03,25,M,0.0,0.309403,0.008448,0.537688,0.600941,0.000000,...,0.202453,0.365391,0.372415,0.293654,0.497615,0.164486,0.385897,0.499127,0.210186,0.220710
58,sub-0025455,04,25,M,0.0,0.362557,0.016340,0.602944,0.648970,0.032366,...,0.000000,0.512593,0.449869,0.395427,0.515643,0.083741,0.501249,0.517737,0.356974,0.299061
59,sub-0025455,05,25,M,0.0,0.210063,0.000000,0.542975,0.544705,0.028385,...,0.130802,0.222342,0.408464,0.282274,0.471772,0.245020,0.350062,0.485285,0.234913,0.321905

# DeepCERES

In [14]:
# Columns to keep and convert
col = {
    'ICV total volume cm3':'ICV',
    'Lobules I-II right volume cm3':'Right.I.II',
    'Lobules I-II left volume cm3':'Left.I.II',
    'Lobule III right volume cm3':'Right.III',
    'Lobule III left volume cm3':'Left.III',
    'Lobule IV right volume cm3':'Right.IV',
    'Lobule IV left volume cm3':'Left.IV',
    'Lobule V right volume cm3':'Right.V',
    'Lobule V left volume cm3':'Left.V',
    'Lobule VI right volume cm3':'Right.VI',
    'Lobule VI left volume cm3':'Left.VI',
    'Crus I right volume cm3':'Right.Crus.I',
    'Crus I left volume cm3':'Left.Crus.I',
    'Crus II right volume cm3':'Right.Crus.II',
    'Crus II left volume cm3':'Left.Crus.II',
    'Lobule VIIB right volume cm3':'Right.VIIB',
    'Lobule VIIB left volume cm3':'Left.VIIB',
    'Lobule VIIIA right volume cm3':'Right.VIIIA',
    'Lobule VIIIA left volume cm3':'Left.VIIIA',
    'Lobule VIIIB right volume cm3':'Right.VIIIB',
    'Lobule VIIIB left volume cm3':'Left.VIIIB',
    'Lobule IX right volume cm3':'Right.IX',
    'Lobule IX left volume cm3':'Left.IX',
    'Lobule X right volume cm3':'Right.X',
    'Lobule X left volume cm3':'Left.X',
}

In [15]:
# List to store DataFrames
all_data = []

# Loop through subjects and sessions
for sub in subjects_list:
    sessions = subjects[subjects['ID']==sub]['good_ses'].iloc[0].split(';')
    for ses in sessions:
        ses_str = f"{int(ses):02d}"
        
        # Get the matching file (for given subject and given session)
        dataFile = glob.glob(os.path.join(deepCeres, 'output', f"{sub}_ses-{ses_str}_T1w_job*_archive", "report_job*.csv"))[0]

        # Read CSV
        data = pd.read_csv(dataFile, sep=';')

        # Keep only the columns in col and rename them
        data = data[list(col.keys())].rename(columns=col)

        # Group I.II, III, IV and V into I.V
        data.insert(4, "Left.I.V", data["Left.I.II"] + data["Left.III"] + data["Left.IV"] + data["Left.V"])
        data.insert(4, "Right.I.V", data["Right.I.II"] + data["Right.III"] + data["Right.IV"] + data["Right.V"])
        data = data.drop(["Left.I.II", "Left.III", "Left.IV", "Left.V", "Right.I.II", "Right.III", "Right.IV", "Right.V"], axis = 1)

        # Add Subject ID and Session columns at the beginning
        data.insert(0, 'ses', ses_str)
        data.insert(0, 'ID', sub)

        # Append to the list
        all_data.append(data)

# Concatenate all DataFrames into one
deepCeres_df = pd.concat(all_data, ignore_index=True)

# Merge with age and sex
deepCeres_df= deepCeres_df.merge(subjects, on="ID", how="left")

# Sort columns
deepCeres_df = deepCeres_df[finalColumns]

# Save it
if save :
    deepCeres_df.to_csv(deepCeres+'deepCeres_all_volumes_cm3.csv', index=False)

deepCeres_df

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,1351.732163,4.844692,5.276966,7.886563,7.846398,10.797028,...,3.567770,4.070928,4.578120,5.000307,2.880662,3.242694,3.261492,3.021514,0.666475,0.618700
1,sub-0025428,04,28,F,1356.510079,4.818477,5.325366,8.020314,7.860640,11.267158,...,3.643464,4.126064,4.510401,5.122244,2.848390,3.217787,3.169573,2.979283,0.570411,0.569861
2,sub-0025428,05,28,F,1353.522653,4.743133,5.256121,7.954060,7.767444,11.154665,...,3.610375,4.000871,4.630597,4.910384,2.731005,3.175029,3.135751,3.005220,0.544502,0.555007
3,sub-0025428,06,28,F,1356.212790,4.787504,5.296738,8.009532,7.717831,11.062090,...,3.526227,3.926097,4.524477,4.931424,2.692483,3.078751,3.038222,2.890901,0.563182,0.525226
4,sub-0025428,07,28,F,1349.206081,4.636417,5.406824,8.077539,7.843083,11.291785,...,3.508983,4.066855,4.551019,4.952618,2.949011,3.299096,3.163647,3.089757,0.601073,0.607284
5,sub-0025432,01,21,M,1582.788179,4.663231,4.998718,6.956390,6.838561,9.440628,...,5.201936,4.592492,4.673277,5.665507,2.888371,2.745428,2.609810,2.425428,0.601073,0.637802
6,sub-0025432,03,21,M,1582.035348,4.692295,5.048955,7.149536,6.899969,9.338888,...,5.241238,4.921434,4.786962,5.625594,2.917310,2.819484,2.583500,2.615196,0.574848,0.577797
7,sub-0025432,04,21,M,1589.019340,4.766156,5.130192,6.945039,6.770866,9.401342,...,4.962192,4.538633,4.938864,5.778867,3.062612,2.902457,2.593863,2.578904,0.459857,0.495424
8,sub-0025432,05,21,M,1586.525482,4.692384,5.011493,6.944745,6.811196,9.439511,...,5.015381,4.683032,4.967257,5.636472,2.899826,2.813350,2.545202,2.578720,0.610479,0.615732
9,sub-0025432,06,21,M,1585.979735,4.741451,5.024970,6.876808,6.818585,9.414343,...,5.226640,4.671521,4.851041,5.782286,2.774750,2.841306,2.567069,2.541544,0.621463,0.637812
10,sub-0025434,03,24,M,1402.347482,4.305733,4.846783,6.362117,6.291957,7.897685,...,3.266066,3.540338,3.850674,4.424790,2.885757,3.152629,2.324942,2.075681,0.493933,0.477728
11,sub-0025434,05,24,M,1405.291993,4.321827,4.813056,6.362219,6.212109,7.757220,...,3.204526,3.460364,3.837572,4.217985,2.741096,3.105206,2.319976,1.906866,0.470874,0.476811
12,sub-0025434,07,24,M,1397.734095,4.184140,4.784538,6.558972,6.240544,7.823734,...,3.265313,3.757362,4.038586,4.044087,2.881521,3.004603,2.326252,2.027498,0.521327,0.477969
13,sub-0025434,08,24,M,1396.860166,4.255782,4.801543,6.456606,6.311951,7.944207,...,3.310591,3.531483,3.940408,4.177683,2.884165,3.145829,2.343710,1.993708,0.508620,0.464218
14,sub-0025434,09,24,M,1400.063383,4.280361,4.780256,6.557767,6.429021,7.886542,...,3.360965,3.315895,3.965525,4.213927,2.793324,3.116406,2.280310,2.047088,0.500458,0.479000
15,sub-0025435,01,30,F,1295.935550,4.108866,3.878657,5.224754,5.358869,7.573198,...,3.364593,2.952005,3.955306,3.903136,2.614851,3.041328,2.333600,2.129259,0.507988,0.491408
16,sub-0025435,02,30,F,1289.948789,4.162123,3.856038,5.369116,5.474493,7.616660,...,3.374924,3.065060,4.091356,3.943037,2.681337,3.093487,2.380920,2.193611,0.544151,0.508338
17,sub-0025435,03,30,F,1291.778040,4.090817,3.876628,5.303579,5.489992,7.842883,...,3.415384,2.970443,3.988165,3.934424,2.634537,2.991663,2.373507,2.147155,0.527925,0.505152
18,sub-0025435,04,30,F,1297.339088,4.083261,3.878104,5.316118,5.328232,7.604912,...,3.260891,3.037694,3.889521,3.869738,2.637055,3.006145,2.331063,2.098367,0.546968,0.495461
19,sub-0025435,05,30,F,1296.897106,4.187104,3.925426,5.240263,5.453317,7.637275,...,3.325476,3.030163,4.025287,3.969431,2.685529,3.019880,2.338455,2.102919,0.544443,0.502616
20,sub-0025440,01,24,M,1482.434544,4.215766,4.429314,5.624088,5.836951,7.768769,...,3.866279,4.089124,4.128663,3.894661,2.970296,2.979985,2.741187,2.662501,0.511459,0.520952
21,sub-0025440,02,24,M,1489.906473,4.247770,4.600912,5.724779,5.745129,7.896797,...,3.787789,4.090054,4.130356,3.785993,2.985340,2.967384,2.747818,2.659932,0.469359,0.511057
22,sub-0025440,03,24,M,1479.686993,4.230921,4.607817,5.688863,5.905289,7.915300,...,3.897943,4.005218,4.197466,3.983605,3.004605,2.972925,2.753045,2.762223,0.519995,0.499271
23,sub-0025440,04,24,M,1481.659603,4.365777,4.752588,5.828898,5.731114,7.367396,...,3.961374,3.807967,4.155665,4.034983,2.398111,2.680947,2.658442,2.540020,0.520760,0.507297
24,sub-0025440,05,24,M,1485.816167,4.198472,4.476871,5.611683,5.925152,7.715880,...,3.825670,4.041394,3.973612,3.812015,3.004031,3.055408,2.815125,2.725633,0.529586,0.508367
25,sub-0025445,01,23,F,1413.397271,4.923989,4.840451,5.795282,6.090952,8.261611,...,3.515652,3.706542,4.187768,4.105944,2.377361,2.881067,1.886229,1.898326,0.500562,0.433598
26,sub-0025445,02,23,F,1414.706418,4.997707,4.782021,5.603877,6.096914,8.304852,...,3.460684,3.708404,4.120727,3.785847,2.367153,2.934072,1.843043,1.850739,0.467832,0.454267
27,sub-0025445,04,23,F,1408.170622,5.018346,4.861410,5.805036,6.230857,8.520911,...,3.589295,3.697422,4.102898,4.151517,2.396079,3.053628,1.876364,1.999391,0.470810,0.453044
28,sub-0025445,05,23,F,1412.734264,4.966257,4.810426,5.829630,6.110833,8.422041,...,3.628038,3.773271,4.089898,3.877827,2.481840,3.085590,1.855937,1.935667,0.460046,0.450115
29,sub-0025445,06,23,F,1418.271115,4.931850,4.769740,5.835024,6.167907,8.178152,...,3.562051,3.817163,4.067896,4.141384,2.471827,3.125504,1.875645,1.915054,0.459202,0.450635
30,sub-0025446,01,30,M,1484.729097,4.179272,4.567174,6.213119,5.740082,9.113815,...,3.940622,3.745363,4.534534,4.510708,3.202881,2.902439,2.820306,2.544465,0.611636,0.553523
31,sub-0025446,02,30,M,1486.374850,4.259640,4.397437,6.258952,5.632843,9.501348,...,4.134283,3.729931,4.399672,4.696546,3.232289,2.980893,2.844263,2.614343,0.582380,0.547493
32,sub-0025446,03,30,M,1477.519542,4.159388,4.487881,6.085995,5.483019,9.269665,...,4.219966,3.780463,4.501020,4.969991,3.369461,2.835951,2.936334,2.701849,0.637082,0.617855
33,sub-0025446,04,30,M,1481.460517,4.251103,4.625362,6.030958,5.533171,9.132125,...,4.152996,3.708563,4.434656,4.748021,3.219959,3.002962,2.866288,2.638852,0.580043,0.536450
34,sub-0025446,05,30,M,1478.416394,4.170420,4.555608,6.330646,5.649457,9.253800,...,4.200794,3.737156,4.680586,4.926480,3.322465,2.924218,2.760353,2.753679,0.615411,0.540927
35,sub-0025447,01,26,M,1659.914387,4.474012,4.567132,6.814732,6.205702,9.712219,...,4.345143,3.892255,3.952343,3.560629,2.513813,2.827510,2.470676,2.259661,0.586647,0.588820
36,sub-0025447,02,26,M,1648.771575,4.475459,4.599026,6.809766,6.099041,9.825722,...,4.419127,4.071621,3.915559,3.557150,2.388821,3.239574,2.435747,2.263758,0.590899,0.616232
37,sub-0025447,03,26,M,1653.931393,4.572022,4.564596,6.676424,6.222590,9.826463,...,4.273269,3.953099,3.789947,3.657036,2.484947,3.032194,2.342781,2.128079,0.565005,0.414122
38,sub-0025447,04,26,M,1655.408062,4.600912,4.546345,6.686261,6.009906,10.033091,...,4.314139,3.929059,3.796232,3.336216,2.351325,2.783039,2.399996,2.160286,0.629185,0.649018
39,sub-0025447,05,26,M,1650.828210,4.474927,4.375897,6.794381,6.198279,9.686220,...,4.381559,3.426087,3.811630,4.058190,2.399575,2.757022,2.471257,2.133252,0.615544,0.605075
40,sub-0025448,01,23,M,1590.909466,5.982293,6.546360,8.414249,9.167364,9.870009,...,5.085511,5.100885,6.003604,6.215024,3.752531,4.056830,3.608439,3.279118,0.575094,0.523883
41,sub-0025448,02,23,M,1594.234076,5.974274,6.669401,8.387343,8.837049,9.905048,...,5.144875,5.244407,5.884759,6.202963,3.692600,4.065260,3.587207,3.342107,0.556911,0.541033
42,sub-0025448,03,23,M,1595.630566,6.061747,6.652795,8.431037,9.000840,9.831536,...,5.363197,5.221809,5.949252,6.187095,3.818123,4.126713,3.556698,3.311632,0.567147,0.549938
43,sub-0025448,05,23,M,1595.443343,5.824232,6.451352,8.460753,8.982379,9.805494,...,5.231780,5.306222,5.919518,5.999171,3.745600,4.151415,3.559602,3.389129,0.582136,0.548212
44,sub-0025448,06,23,M,1588.069707,6.031032,6.665113,8.562691,9.157653,9.877077,...,5.221919,5.186933,6.009723,6.125386,3.772363,4.140875,3.651823,3.408517,0.534956,0.555629
45,sub-0025449,02,22,M,1670.729768,5.961295,5.656642,7.913072,8.021591,10.485052,...,4.683422,5.065572,5.408472,4.423800,3.460364,3.447021,3.407328,3.135364,0.669791,0.602078
46,sub-0025449,03,22,M,1674.987395,6.030129,5.775400,7.852959,8.018477,10.328772,...,4.658069,5.050375,5.350888,4.470781,3.467686,3.754509,3.478796,3.135528,0.672396,0.585765
47,sub-0025449,04,22,M,1678.903959,6.022467,5.732757,7.832075,8.002212,10.279667,...,4.407890,5.128110,5.335363,4.357771,3.378734,3.553983,3.421518,3.032570,0.646098,0.558529
48,sub-0025449,05,22,M,1673.397749,6.058738,5.747404,7.886632,8.020957,10.419648,...,4.565703,5.134483,5.323367,4.566935,3.482925,3.605263,3.495361,3.101349,0.693583,0.572253
49,sub-0025449,06,22,M,1678.242647,6.070975,5.750942,7.955039,8.142436,10.405333,...,4.605354,5.188303,5.389614,4.648893,3.516659,3.602278,3.516771,3.163186,0.704252,0.580256
50,sub-0025450,01,25,F,1348.188274,4.465618,4.033964,5.551644,5.612759,7.691393,...,3.544684,3.918087,3.971864,3.811336,2.676275,2.721999,2.262696,2.145029,0.480421,0.498586
51,sub-0025450,02,25,F,1347.279206,4.381267,3.984389,5.669402,5.598929,7.731490,...,3.590812,3.943443,3.993488,4.060303,2.793399,2.749509,2.249688,2.141927,0.550847,0.485281
52,sub-0025450,03,25,F,1347.840261,4.361743,4.129883,6.036560,5.849537,7.842044,...,3.795581,4.067006,4.654871,4.598068,2.458906,2.438096,2.344852,2.508743,0.511144,0.466220
53,sub-0025450,04,25,F,1351.116052,4.423743,3.965159,5.512848,5.535469,7.702144,...,3.544663,3.815129,4.014335,3.934134,2.700990,2.719051,2.288273,2.166764,0.514555,0.466721
54,sub-0025450,05,25,F,1344.329852,4.432897,3.971798,5.604408,5.573745,7.695621,...,3.614810,4.102026,3.926874,3.965380,2.873379,2.742171,2.246577,2.219836,0.526168,0.522781
55,sub-0025455,01,25,M,1481.792947,4.201720,4.748573,6.819779,7.055006,7.872370,...,3.931511,3.536852,4.024496,4.541795,1.823111,2.836800,2.583378,2.444051,0.506141,0.525140
56,sub-0025455,02,25,M,1485.886966,4.126657,4.679981,6.887458,6.969715,7.848452,...,3.996752,3.633119,4.231383,4.530114,2.576126,2.926317,2.762005,2.504001,0.515406,0.475481
57,sub-0025455,03,25,M,1481.577652,4.088495,4.752850,6.880130,6.912882,7.851072,...,3.865240,3.612238,3.955985,4.586086,2.640094,2.917535,2.783221,2.524410,0.505904,0.492282
58,sub-0025455,04,25,M,1478.373278,4.023245,4.863607,6.892915,6.987371,8.034231,...,3.958030,3.608541,3.984357,4.547680,2.558566,2.841333,2.766169,2.536660,0.485949,0.481929
59,sub-0025455,05,25,M,1482.297973,3.983556,4.735645,6.915871,6.816957,7.883646,...,3.923565,3.620502,4.023482,4.489061,2.666170,2.839822,2.769799,2.538465,0.518648,0.460062

In [16]:
# Scale data
scaler = MinMaxScaler()

# Divide by ICV and scale
deepCeres_scaled = deepCeres_df.copy()
deepCeres_scaled.iloc[:, 4:] = scaler.fit_transform(deepCeres_scaled.iloc[:, 4:].div(deepCeres_scaled.ICV, axis=0))

# Save the dataframe
if save :
    deepCeres_scaled.to_csv(deepCeres+'deepCeres_all_volumes_cm3_scaled.csv', index=False)

deepCeres_scaled

,ID,ses,age,sex,ICV,Left.I.V,Right.I.V,Left.VI,Right.VI,Left.Crus.I,...,Left.VIIB,Right.VIIB,Left.VIIIA,Right.VIIIA,Left.VIIIB,Right.VIIIB,Left.IX,Right.IX,Left.X,Right.X
0,sub-0025428,02,28,F,0.0,0.806662,0.810423,0.931010,0.996147,0.887642,...,0.332219,0.748719,0.733765,0.890336,0.774824,0.777501,1.000000,0.945418,1.000000,1.000000
1,sub-0025428,04,28,F,0.0,0.777919,0.824606,0.966326,0.991589,0.981389,...,0.375244,0.772740,0.692333,0.930977,0.747902,0.748900,0.931300,0.906545,0.643744,0.818567
2,sub-0025428,05,28,F,0.0,0.734893,0.797123,0.950082,0.965903,0.962318,...,0.358111,0.704142,0.756735,0.852620,0.677288,0.720786,0.913435,0.930474,0.554309,0.770104
3,sub-0025428,06,28,F,0.0,0.758073,0.811511,0.963315,0.943927,0.937411,...,0.295810,0.655363,0.699774,0.857018,0.649411,0.640091,0.844512,0.842076,0.618021,0.660264
4,sub-0025428,07,28,F,0.0,0.673822,0.877396,1.000000,1.000000,1.000000,...,0.296479,0.750814,0.724558,0.875309,0.821832,0.826888,0.938739,1.000000,0.766510,0.963321
5,sub-0025432,01,21,M,0.0,0.232823,0.328175,0.279717,0.316181,0.292086,...,0.930969,0.660659,0.442842,0.827025,0.511407,0.068772,0.311783,0.244871,0.443683,0.735931
6,sub-0025432,03,21,M,0.0,0.250612,0.349683,0.335905,0.334907,0.273989,...,0.955400,0.828037,0.491921,0.814585,0.527889,0.119589,0.297508,0.365146,0.363176,0.553907
7,sub-0025432,04,21,M,0.0,0.280702,0.373675,0.268686,0.288901,0.277922,...,0.779455,0.624456,0.547048,0.857324,0.599576,0.166937,0.296918,0.335143,0.000000,0.296125
8,sub-0025432,05,21,M,0.0,0.243111,0.328571,0.271711,0.303616,0.287742,...,0.815014,0.700831,0.562310,0.812890,0.513920,0.110084,0.271598,0.337570,0.468401,0.664254
9,sub-0025432,06,21,M,0.0,0.271860,0.334770,0.253010,0.306427,0.283673,...,0.939261,0.695838,0.513945,0.862149,0.446623,0.129539,0.284516,0.314765,0.503060,0.732048
10,sub-0025434,03,24,M,0.0,0.344526,0.520911,0.343851,0.392306,0.194113,...,0.045031,0.359224,0.304391,0.602742,0.711784,0.616622,0.319913,0.192817,0.308471,0.435441
11,sub-0025434,05,24,M,0.0,0.349041,0.500706,0.339583,0.361966,0.161213,...,0.000000,0.309485,0.294291,0.521434,0.619526,0.575597,0.313600,0.070003,0.224276,0.428850
12,sub-0025434,07,24,M,0.0,0.275379,0.499488,0.414353,0.382238,0.184010,...,0.051644,0.490054,0.400520,0.464231,0.715019,0.511561,0.325687,0.163330,0.410415,0.441696
13,sub-0025434,08,24,M,0.0,0.323206,0.508746,0.382522,0.406939,0.210431,...,0.082986,0.362086,0.354649,0.515758,0.717757,0.620849,0.337883,0.140126,0.366892,0.395246
14,sub-0025434,09,24,M,0.0,0.332728,0.493827,0.410431,0.440513,0.194475,...,0.111258,0.234321,0.362343,0.525828,0.657881,0.592934,0.293631,0.174870,0.334175,0.442505
15,sub-0025435,01,30,F,0.0,0.434673,0.221315,0.115297,0.231219,0.256539,...,0.292305,0.161953,0.509512,0.526895,0.677314,0.721925,0.448568,0.355151,0.503733,0.621279
16,sub-0025435,02,30,F,0.0,0.485055,0.218958,0.174401,0.281079,0.274442,...,0.310863,0.240495,0.589652,0.550641,0.729705,0.776679,0.489143,0.412469,0.650326,0.693076
17,sub-0025435,03,30,F,0.0,0.431284,0.226529,0.148778,0.283822,0.323536,...,0.336413,0.179230,0.533132,0.544827,0.696009,0.688968,0.481619,0.374228,0.585715,0.678486
18,sub-0025435,04,30,F,0.0,0.413831,0.218946,0.145188,0.218349,0.261874,...,0.215752,0.212802,0.473332,0.511560,0.690158,0.690287,0.445051,0.329647,0.649187,0.634370
19,sub-0025435,05,30,F,0.0,0.486831,0.243203,0.119355,0.263180,0.269808,...,0.262619,0.208796,0.544143,0.552743,0.722906,0.702427,0.450738,0.333695,0.640332,0.661610
20,sub-0025440,01,24,M,0.0,0.140699,0.218033,0.007684,0.140628,0.078943,...,0.303218,0.546195,0.330636,0.323524,0.665210,0.362824,0.492174,0.507640,0.273087,0.487309
21,sub-0025440,02,24,M,0.0,0.147194,0.282828,0.029655,0.103345,0.096503,...,0.242376,0.535632,0.322040,0.277993,0.665252,0.343047,0.487829,0.496944,0.125843,0.446776
22,sub-0025440,03,24,M,0.0,0.154664,0.299639,0.030680,0.165138,0.110961,...,0.327497,0.504945,0.365248,0.357887,0.688355,0.361715,0.502486,0.578130,0.304561,0.419781
23,sub-0025440,04,24,M,0.0,0.233122,0.360148,0.071129,0.108845,0.000000,...,0.363861,0.395601,0.343819,0.374327,0.333920,0.148642,0.442735,0.426190,0.304798,0.443742
24,sub-0025440,05,24,M,0.0,0.124405,0.234335,0.000000,0.163720,0.064952,...,0.272439,0.515486,0.256485,0.290952,0.680817,0.412094,0.533212,0.545912,0.329136,0.442597
25,sub-0025445,01,23,F,0.0,0.716459,0.500539,0.146338,0.311079,0.256953,...,0.191562,0.437478,0.449775,0.470418,0.388533,0.392908,0.028613,0.056226,0.317980,0.271997
26,sub-0025445,02,23,F,0.0,0.760438,0.471779,0.083403,0.311182,0.264359,...,0.153484,0.436590,0.416194,0.349359,0.380987,0.430865,0.000000,0.021463,0.202767,0.341097
27,sub-0025445,04,23,F,0.0,0.788374,0.518385,0.156359,0.363926,0.317549,...,0.248489,0.440083,0.416769,0.493231,0.405338,0.531705,0.026764,0.132723,0.220690,0.344096
28,sub-0025445,05,23,F,0.0,0.744847,0.487834,0.158210,0.318453,0.291192,...,0.266244,0.476234,0.404300,0.385760,0.452828,0.548367,0.009861,0.083196,0.177972,0.329083
29,sub-0025445,06,23,F,0.0,0.710675,0.460684,0.152642,0.329153,0.233716,...,0.213921,0.492644,0.386337,0.478352,0.440856,0.569293,0.017759,0.063381,0.168808,0.324851
30,sub-0025446,01,30,M,0.0,0.114632,0.275096,0.184542,0.107948,0.343255,...,0.345815,0.357633,0.510872,0.540769,0.797298,0.303792,0.537605,0.425640,0.601772,0.590504
31,sub-0025446,02,30,M,0.0,0.160472,0.199041,0.196398,0.072932,0.418010,...,0.463641,0.347097,0.447827,0.605099,0.812262,0.357790,0.550230,0.470604,0.502883,0.568944
32,sub-0025446,03,30,M,0.0,0.114882,0.250096,0.154851,0.036879,0.383126,...,0.532718,0.386474,0.505660,0.712969,0.903334,0.265964,0.616699,0.540135,0.696206,0.809292
33,sub-0025446,04,30,M,0.0,0.163840,0.304887,0.133083,0.047867,0.350881,...,0.483864,0.342220,0.470224,0.629013,0.811308,0.380779,0.569342,0.492907,0.501521,0.538884
34,sub-0025446,05,30,M,0.0,0.120059,0.278531,0.228597,0.087427,0.378846,...,0.519117,0.361808,0.585784,0.696328,0.874799,0.328412,0.508380,0.573969,0.622946,0.557086
35,sub-0025447,01,26,M,0.0,0.007114,0.065124,0.148701,0.049527,0.258666,...,0.312128,0.215498,0.060004,0.068592,0.244367,0.035548,0.167255,0.074382,0.314369,0.503288
36,sub-0025447,02,26,M,0.0,0.024292,0.089659,0.159893,0.031464,0.290574,...,0.370011,0.315168,0.055838,0.075142,0.187960,0.314439,0.157233,0.086027,0.338759,0.595044
37,sub-0025447,03,26,M,0.0,0.069198,0.070569,0.117583,0.060401,0.285233,...,0.280683,0.251701,0.000000,0.103516,0.234067,0.174142,0.102444,0.000000,0.256396,0.000000
38,sub-0025447,04,26,M,0.0,0.082680,0.061846,0.118643,0.000000,0.320418,...,0.301393,0.238382,0.001174,0.000000,0.163480,0.011836,0.132442,0.018246,0.445270,0.683347
39,sub-0025447,05,26,M,0.0,0.020959,0.000000,0.153347,0.056895,0.263511,...,0.345867,0.000000,0.011684,0.234201,0.192011,0.000000,0.174952,0.005534,0.409873,0.560199
40,sub-0025448,01,23,M,0.0,0.965212,0.946881,0.684203,0.976740,0.362578,...,0.847739,0.904364,0.992899,1.000000,0.970643,0.938680,0.869679,0.771874,0.353983,0.380621
41,sub-0025448,02,23,M,0.0,0.953632,0.991244,0.671575,0.876307,0.365240,...,0.876023,0.971010,0.937690,0.991692,0.934075,0.938647,0.853420,0.806967,0.294278,0.429197
42,sub-0025448,03,23,M,0.0,1.000000,0.982146,0.681882,0.921114,0.350076,...,1.000000,0.957382,0.962601,0.984633,1.000000,0.977351,0.834421,0.786104,0.324275,0.454684
43,sub-0025448,05,23,M,0.0,0.866470,0.900806,0.690591,0.916116,0.345483,...,0.924156,1.000000,0.950410,0.922593,0.961140,0.994192,0.836296,0.834758,0.370612,0.449660
44,sub-0025448,06,23,M,0.0,0.998872,1.000000,0.730777,0.978659,0.367154,...,0.932498,0.952280,1.000000,0.973849,0.985014,1.000000,0.897943,0.856755,0.233052,0.479884
45,sub-0025449,02,22,M,0.0,0.792282,0.475342,0.434136,0.536406,0.383694,...,0.483778,0.764964,0.633510,0.334426,0.723280,0.419348,0.663619,0.587979,0.547494,0.530487
46,sub-0025449,03,22,M,0.0,0.821094,0.515629,0.412450,0.529963,0.351530,...,0.463182,0.751546,0.604968,0.345699,0.722512,0.609588,0.697387,0.583322,0.550126,0.479094
47,sub-0025449,04,22,M,0.0,0.809433,0.494001,0.401872,0.520407,0.338685,...,0.319313,0.782947,0.593782,0.306815,0.672782,0.476595,0.662288,0.517852,0.468615,0.396910
48,sub-0025449,05,22,M,0.0,0.839551,0.506928,0.423570,0.532725,0.369242,...,0.414558,0.794030,0.595984,0.377422,0.732037,0.516716,0.708082,0.564738,0.614167,0.441749
49,sub-0025449,06,22,M,0.0,0.836708,0.501879,0.435857,0.559549,0.361439,...,0.429130,0.812592,0.616275,0.399078,0.744159,0.508184,0.714142,0.596129,0.639508,0.459988
50,sub-0025450,01,25,F,0.0,0.562182,0.220796,0.154304,0.244071,0.215670,...,0.322795,0.664391,0.438498,0.429169,0.649235,0.372220,0.338317,0.303342,0.328735,0.576073
51,sub-0025450,02,25,F,0.0,0.507867,0.198305,0.195110,0.240655,0.225565,...,0.356113,0.681010,0.450581,0.527887,0.725167,0.395456,0.330640,0.302117,0.586589,0.529644
52,sub-0025450,03,25,F,0.0,0.493617,0.267320,0.317575,0.325049,0.249009,...,0.495646,0.753347,0.778462,0.738187,0.510949,0.148075,0.393619,0.572693,0.441113,0.460707
53,sub-0025450,04,25,F,0.0,0.527842,0.183669,0.137274,0.213728,0.214373,...,0.317510,0.598417,0.455278,0.473986,0.661269,0.365225,0.352095,0.315939,0.448994,0.458451
54,sub-0025450,05,25,F,0.0,0.548837,0.196444,0.177411,0.236249,0.221416,...,0.378039,0.780479,0.421744,0.494048,0.780257,0.394409,0.331855,0.363352,0.500851,0.668004
55,sub-0025455,01,25,M,0.0,0.133279,0.358209,0.373543,0.518024,0.100194,...,0.344992,0.249102,0.284352,0.555045,0.000000,0.260670,0.396954,0.361488,0.256197,0.501675
56,sub-0025455,02,25,M,0.0,0.080803,0.322644,0.388415,0.485715,0.091145,...,0.378851,0.295653,0.372609,0.546423,0.433015,0.319311,0.500925,0.397170,0.282194,0.335767
57,sub-0025455,03,25,M,0.0,0.064897,0.360377,0.392277,0.474390,0.096189,...,0.303965,0.290070,0.253640,0.571087,0.474492,0.319098,0.518696,0.415783,0.255656,0.394952
58,sub-0025455,04,25,M,0.0,0.030571,0.413325,0.400744,0.502109,0.136043,...,0.367266,0.292295,0.270373,0.560898,0.430377,0.268665,0.511973,0.427722,0.193012,0.364649
59,sub-0025455,05,25,M,0.0,0.000000,0.351862,0.402166,0.443702,0.101900,...,0.339196,0.293580,0.283274,0.535682,0.488879,0.262149,0.509716,0.424408,0.297057,0.289328